
class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appName': 'MyChart',
      'welcome': 'Welcome',
      'back': 'Back',
      'next': 'Next',
      'getStarted': 'Get Started',
      'studentIdLabel': 'University Email',
      'studentIdHint': 'e.g., username@cihanuniversity.edu.iq',
      'studentPasswordHint': 'Enter your password',
      'studentEmailLoginHint': 'Use your university email to sign in',
      'continueAsGuest': 'Continue as Guest',
      'appTagline': 'Your Health, In Your Hands',
      'featureRecords': 'Records',
      'featureAppointments': 'Appointments',
      'featureMessages': 'Messages',
      'featureHealth': 'Health',
      'navHome': 'Home',
      'navMessages': 'Messages',
      'navChatbot': 'Chatbot AI',
      'navSettings': 'Settings',
      'selectRole': 'Choose Your Role',
      'roleSubtitle': 'Select how you want to access the platform',
      'rolePatient': 'Patient',
      'rolePatientDesc': 'Access medical records & appointments',
      'roleDoctor': 'Doctor',
      'roleDoctorDesc': 'Manage patients & schedules',
      'roleStudent': 'Student',
      'roleStudentDesc': 'Track training & submit reports',
      'universityTools': 'University Tools',
      'seeAll': 'See All',
      'toolHospital': 'Hospital',
      'toolDoctors': 'Doctors',
      'toolReports': 'Reports',
      'toolTasks': 'Tasks',
      'pendingAssignment': 'Pending Assignment',
      'assignmentDesc': 'Submit your Clinical Pathology report by 5:00 PM today.',
      'currentLevel': 'Current Level',
      'year4': 'Year 4',
      'modeClinical': 'Clinical',
      'gpaLabel': 'GPA: {value}',
      'idLabel': 'ID: {value}',
      'navCourses': 'My Courses',
      'navCases': 'Cases',
      'commonCases': 'Common Cases',
      'caseStudyTitle': 'Case Study',
      'hospitalInfo': 'Hospital Info',
      'hospitalName': 'Grand City University Hospital',
      'hospitalAddress': '123 Medical Center Blvd, Cityville',
      'labelDepartments': 'Departments',
      'labelBeds': 'Beds',
      'aboutUs': 'About Us',
      'hospitalDesc': 'Grand City University Hospital is a premier teaching institution dedicated to providing world-class patient care and educating the next generation of healthcare professionals.',
      'closeInfo': 'Close Info',
      'studentName': 'Alex Thompson',
      'titleJoinNewCourse': 'Join New Course',
      'labelNoAvailableCourses': 'No new courses available to join.',
      'actionJoinCourse': 'Join Course',
      'messageJoinSuccess': 'Successfully joined the course!',
      'messageJoinError': 'Failed to join course.',
      'loginTitle': 'Welcome Back',
      'loginSubtitle': 'Sign in to your account',
      'emailLabel': 'Email Address',
      'passwordLabel': 'Password',
      'emailHint': 'Enter your email',
      'passwordHint': 'Enter your password',
      'forgotPassword': 'Forgot Password?',
      'signIn': 'Sign In',
      'orSignInWith': 'Or sign in with',
      'dontHaveAccount': 'Don\'t have an account?',
      'signUp': 'Sign Up',
      'forgotPasswordTitle': 'Reset Password',
      'forgotPasswordSubtitle': 'Enter your credentials to recover your account',
      'sendResetLink': 'Send Reset Link',
      'checkEmail': 'Check your email for instructions',
      'backToLogin': 'Back to Login',
      'identifierLabel': 'Student ID / Email',
      'doctorIdentifierLabel': 'Sheet ID / Email',
      'verificationTitle': 'Verify Code',
      'verificationSubtitle': 'Enter the 6-digit code sent to your email',
      'verifyControl': 'Verify',
      'titleProfile': 'My Profile',
      'labelEmailAddress': 'Email Address',
      'labelPhoneNumber': 'Phone Number',
      'actionEditProfile': 'Edit Profile',
      'gpa': 'GPA',
      'studentId': 'STUDENT ID',
      'labelSubmitReport': 'Submit Report',
      'labelHistory': 'View Submitted Reports',
      'labelReportTitle': 'Report Title',
      'hintReportTitle': 'e.g., Clinical Pathology Report',
      'labelReportDesc': 'Description',
      'hintReportDesc': 'Brief description of your report...',
      'labelAttachFile': 'Attach File',
      'msgFileFormat': 'PDF, DOC, DOCX (Max 10MB)',
      'actionBrowse': 'Browse',
      'actionSubmit': 'Submit',
      'msgReportSubmitted': 'Report submitted successfully!',
      'titleSubmittedReports': 'Submitted Reports',
      'titleAssignments': 'Assignments',
      'labelDue': 'Due: {date}',
      'actionUploadAssignment': 'Upload New Assignment',
      'descUploadAssignment': 'Submit extra credit work',
      'actionView': 'View',
      'titleMarkAttendance': 'Mark Attendance',
      'descScanQR': 'Scan the QR code in your classroom or clinic to mark your attendance.',
      'actionScanQR': 'Scan QR Code',
      'msgAttendanceMarked': 'Attendance marked successfully!',
      'labelAttendance': 'Attendance',
      'resendCode': 'Resend Code',
      'newPasswordTitle': 'New Password',
      'newPasswordSubtitle': 'Set a strong password for your account',
      'newPasswordLabel': 'New Password',
      'confirmNewPasswordLabel': 'Confirm New Password',
      'newPasswordHint': 'Min. 6 characters',
      'resetSuccess': 'Password changed successfully',
      'passwordMismatch': 'Passwords do not match',
      'signUpTitle': 'Create Account',
      'signUpSubtitle': 'Start your health journey today',
      'fullNameLabel': 'Full Name',
      'phoneLabel': 'Phone Number',
      'confirmPasswordLabel': 'Confirm Password',
      'fullNameHint': 'Enter your full name',
      'phoneHint': 'Enter your phone number',
      'confirmPasswordHint': 'Re-enter your password',
      'alreadyHaveAccount': 'Already have an account?',
      'patientInfo': 'Patient Information',
      'details': 'Details',
      'demographics': 'Demographics',
      'bloodType': 'Blood Type',
      'chronicDiseases': 'Chronic Diseases',
      'quickActions': 'Quick Actions',
      'bookAppt': 'Book Appointment',
      'medicalRecords': 'Medical Records',
      'labResults': 'Lab Results',
      'pharmacy': 'Pharmacy',
      'upcomingAppt': 'Upcoming Appointment',
      'viewDetails': 'View Details',
      'confirmed': 'Confirmed',
      'allResults': 'All Results',
      'socialStatus': 'Social Status',
      'socialStatusVal': 'Married, Engineer',
      'weeklySummary': 'Weekly Summary',
      'avgBP': 'Avg BP',
      'entriesRecorded': 'Entries recorded this week',
      'tabOverview': 'Overview',
      'tabVitals': 'Vitals',
      'labelHeartRate': 'Heart Rate',
      'labelBloodPressure': 'Blood Pressure',
      'labelBloodGlucose': 'Blood Glucose',
      'unitBpm': 'bpm',
      'unitMmHg': 'mmHg',
      'unitLbs': 'lbs',
      'unitMgDl': 'mg/dL',
      'labelDiagnosedDate': 'Diagnosed',
      'quickAddVitals': 'Quick Add Vitals',
      'labelBPTrend': 'Blood Pressure Trend',
      'labelHRTrend': 'Heart Rate Trend',
      'labelWeightTrend': 'Weight Trend',
      'labelBGTrend': 'Blood Glucose Trend',
      'labelSystolic': 'Systolic',
      'labelDiastolic': 'Diastolic',
      'save': 'Save',
      'msgSuccess': 'Vitals logged successfully',
      'labelRecentHistory': 'Recent History',
      'labelTreatingPhysician': 'Treating Physician',
      'labelManagementPlan': 'Management Plan',
      'labelLastUpdated': 'Last Updated',
      'chatbotTitle': 'AI Health Assistant',
      'chatbotAlwaysAvailable': 'Always available',
      'chatbotWelcome': 'Hello! I am your AI Health Assistant. How can I help you today?',
      'chatbotTyping': 'Assistant is typing...',
      'chatbotInputHint': 'Ask about your health...',
      'suggestHeadache': 'I have a headache',
      'suggestBookAppt': 'Book appointment',
      'suggestLabResults': 'Check lab results',
      'ageVal': 'Female, 34 yrs',
      'medicalRecordsShort': 'Med Records',
      'pharmacyShort': 'Pharmacy',
      'labResultsShort': 'Lab Results',
      'labResultsTitle': 'Lab Results',
      'labTrends': 'Blood Glucose Trends',
      'labTrendsDesc': 'Extracted from your uploaded lab reports using Smart OCR.',
      'recentLabReports': 'Recent Lab Reports',
      'reportFrom': 'Report from {date}',
      'extractedGlucose': 'Extracted Glucose: {value} mg/dL',
      'noLabResults': 'No lab results available',
      'close': 'Close',
      'studentEmailError': 'Students must use a university email (@cihanuniversity.edu.iq)',
      'navPatients': 'Patients',
      'navSchedule': 'Schedule',
      'doctorPatientListTitle': 'Your Patient List',
      'condHealthy': 'Healthy',
      'doctorInsightsTitle': 'Medical Research & Insights',
      'doctorInsightsSubtitle': 'Stay updated with the latest clinical studies',
      'statTotalPatients': 'Total Patients',
      'statCompletedToday': 'Completed Today',
      'statPendingReviews': 'Pending Reviews',
      'statTodaysAppointments': 'Today\'s Appointments',
      'doctorMyPatientsTitle': 'My Patients',
      'doctorAddPatientTitle': 'Add New Patient',
      'labelPatientName': 'Patient Name',
      'labelAge': 'Age',
      'labelCondition': 'Condition',
      'actionAddPatient': 'Add Patient',
      'msgPatientAdded': 'Patient added successfully',
      'labelLastVisit': 'Last visit',
      'doctorScheduleTitle': 'Appointments Schedule',
      'tabUpcoming': 'Upcoming',
      'tabCompleted': 'Completed',
      'tabCancelled': 'Cancelled',
      'msgNoAppointments': 'No appointments found',
      'actionJoin': 'Join',
      'actionCancel': 'Cancel',
      'actionConfirm': 'Confirm',
      'msgAppointmentConfirmed': 'Appointment confirmed successfully',
      'msgAppointmentCancelled': 'Appointment cancelled successfully',
      'labelUnknownPatient': 'Unknown Patient',
      'labelVisit': 'Visit',
      'labelAt': 'at',
      'errorLoadAppointments': 'Failed to load appointments',
      'errorUpdateStatus': 'Failed to update appointment status',
      'labelManageAvailability': 'Manage Availability',
      'titleCases': 'Library',
      'doctorProfileTitle': 'Profile Info',
      'msgProfileUpdated': 'Profile updated successfully',
      'labelPhone': 'Phone',
      'labelDOB': 'Date of Birth',
      'labelSpecialization': 'Specialization',
      'labelLocation': 'Location',
      'labelNotSet': 'Not set',
      'publishResearch': 'Publish Research',
      'postResearchTitle': 'Share Your Research',
      'labelCommunity': 'Doctor Community',
      'researchSearchHint': 'Search books, journals, or guidelines...',
      'trendingTitle': 'Trending & Popular',
      'knowledgeLibraryTitle': 'Knowledge Library',
      'searchResultsTitle': 'Search Results ({count})',
      'noResultsFound': 'No resources found for this search.',
      'sectAccount': 'Account',
      'sectAppearance': 'Appearance',
      'optDarkMode': 'Dark Mode',
      'optLightMode': 'Light Mode',
      'optEditInfo': 'Edit Info',
      'sectHelp': 'Help',
      'sectPreferences': 'Preferences',
      'sectSupport': 'Support',
      'sectAcademicManagement': 'Academic Management',
      'optPersonalInfo': 'Personal Info',
      'subPersonalInfo': 'Edit your registered profile details',
      'optAcademicManagement': 'Academic Management',
      'subAcademicManagement': 'View student submissions and manage assigned tasks',
      'optReportIssue': 'Report an Issue',
      'optContactSupport': 'Contact Support',
      'sectSecurityUpdate': 'Security Update',
      'subSecurityUpdate': 'Keep your account safe by updating your password regularly',
      'labelCurrentPassword': 'Current Password',
      'labelNewPassword': 'New Password',
      'labelConfirmNewPassword': 'Confirm New Password',
      'actionUpdatePassword': 'Update Password',
      'msgPasswordUpdated': 'Password updated successfully',
      'errorRequired': 'Required field',
      'errorPasswordShort': 'Password too short (min 6 chars)',
      'errorPasswordsMismatch': 'Passwords do not match',
      'optChangePassword': 'Change Password',
      'optHelpCenter': 'Help Center',
      'labelDeveloper': 'Developer',
      'labelContactEmail': 'Contact Email',
      'optAboutApp': 'About App',
      'labelMission': 'Our Mission',
      'labelCredits': 'Developer Credits',
      'labelVersion': 'Version',
      'tabSyllabus': 'Syllabus',
      'tabAssignments': 'Assignments',
      'tabResources': 'Resources',
      'sectCourseOverview': 'Course Overview',
      'sectModules': 'Modules',
      'sectUpcoming': 'Upcoming',
      'sectPast': 'Past',
      'actionContactInstructor': 'Contact Instructor',
      'msgContactingInstructor': 'Contacting instructor...',
      'manageSchedule': 'Manage Schedule',
      'latestVitals': 'Latest Vitals',
      'bpLabel': 'BP',
      'bpmLabel': 'BPM',
      'kgLabel': 'KG',
      'healthAlert': 'Health Alert',
      'highBPAlert': 'High Blood Pressure Alert',
      'highBPMessage': 'DANGER: Your last reading was {sys}/{dia}. Please rest and consult your doctor.',
      'confirm': 'Confirm',
      'cancelAptTitle': 'Cancel Appointment',
      'cancelAptConfirm': 'Are you sure you want to cancel your appointment with {doctor} on {date} at {time}?',
      'errorCancelApt': 'Failed to cancel appointment. Please try again.',
      'sampleCoursesSeeded': 'Sample courses seeded successfully!',
      'coursesExistOrFailed': 'Courses already exist or failed to seed.',
      'actionSeedCourses': 'Seed Sample Courses',
      'bookingTitle': 'Book Appointment',
      'searchDoctor': 'Search for a doctor...',
      'specAll': 'All',
      'specCardiology': 'Cardiology',
      'specNeurology': 'Neurology',
      'specOphthalmology': 'Ophthalmology',
      'specOrthopedics': 'Orthopedics',
      'specPediatrics': 'Pediatrics',
      'labelDoctorCount': '{count} doctors found',
      'selectDateTime': 'Select Date & Time',
      'labelSelectDate': 'SELECT DATE',
      'labelSelectTime': 'SELECT TIME',
      'confirmAppt': 'Confirm Appointment',
      'apptSuccessTitle': 'Appointment Booked!',
      'apptSuccessDesc': 'Your appointment has been successfully scheduled. You can view it in your dashboard.',
      'labelDoctorInfo': 'DOCTOR INFORMATION',
      'labelDate': 'DATE',
      'labelTime': 'TIME',
      'labelDone': 'Done',
      'callMyDoctors': 'Call My Doctors',
      'healthUpdate': 'Health Update',
      'labPendingReview': '{count} Lab reports pending review',
      'labelYears': 'years',
      'labelNone': 'None',
      'labelSingle': 'Single',
      'profileTitle': 'Patient Profile',
      'labelPatient': 'Patient',
      'unitYears': 'years',
      'labelBlood': 'Blood Type',
      'labelNotAvailable': 'Not Available',
      'actionLogout': 'Logout',
      'actionEditMedicalProfile': 'Edit Medical Profile',
      'actionSave': 'Save',
      'sectPersonalInfo': 'Personal Information',
      'sectChronicConditions': 'Chronic Conditions',
      'labelHeight': 'Height',
      'labelWeight': 'Weight',
      'labelDOBShort': 'Date of Birth',
      'labelSocialStatus': 'Social Status',
      'msgNoConditions': 'No conditions recorded',
      'actionAddCondition': 'Add Condition',
      'labelConditionName': 'Condition Name',
      'labelStatusHint': 'Current Status (e.g., Stable)',
      'msgMedicalProfileUpdated': 'Medical profile updated successfully',
      'labelStatus': 'Status:',
      'actionAdd': 'Add',
      'labelUnknownUser': 'Unknown User',
      'msgNoDoctorsAvailable': 'No doctors available in the database.',
      'hintSelectDoctor': 'Select a Doctor',
      'msgTitleDoctorRequired': 'Title and Doctor are required',
      'msgReportSubmitError': 'Failed to submit report',
      'msgNoReports': 'No reports submitted yet.',
      'msgSubmittedAt': 'Submitted: {date}\nTo Doctor ID: {id}',
      'msgNoTasks': 'No tasks assigned yet.',
      'msgNoCoursesEnrolled': 'No courses enrolled yet.',
      'labelSupervisorDoctor': 'Supervisor (Doctor)',
      'labelFileAttached': 'File Attached',
      'errorLoadReports': 'Error loading reports',
      'actionViewCaseStudy': 'View Case Study',
      'titleFindDoctor': 'Find a Doctor',
      'labelBy': 'By ',
      'titleMyCourses': 'My Courses',
      'labelSemester1_2026': 'Semester 1, 2026',
      'labelResumeLearning': 'Resume Learning',
      'labelInProgress': 'In Progress',
      'labelGrade': 'Grade: {grade}',
      'labelProgress': 'Progress',
      'labelNext': 'Next: {time}',
      'actionViewDetails': 'View Details',
      'labelCaseStudy': 'Case Study #{id}',
      'labelCardiology': 'Cardiology',
      'titleCaseStudy': 'Complex Type 1 Diabetes',
      'labelCaseDuration': '2 hours',
      'labelPriority': 'High Priority',
      'tabClinical': 'Clinical',
      'tabLabs': 'Labs',
      'tabDiagnosis': 'Diagnosis',
      'labelChiefComplaint': 'Chief Complaint',
      'labelPatientDemographics': 'Patient Demographics',
      'labelInitialVitals': 'Initial Vitals',
      'labelLearningObjectives': 'Learning Objectives',
      'actionCompleteCase': 'Complete Case',
      'actionTakeNotes': 'Take Notes',
    },
    'ar': {
      'appName': 'MyChart',
      'welcome': 'مرحباً',
      'seeAll': 'عرض الكل',
      'back': 'رجوع',
      'next': 'التالي',
      'getStarted': 'ابدأ الآن',
      'navHome': 'الرئيسية',
      'navMessages': 'الرسائل',
      'navChatbot': 'المساعد الذكي',
      'navSettings': 'الإعدادات',
      'rolePatient': 'مريض',
      'roleDoctor': 'طبيب',
      'roleStudent': 'طالب',
      'rolePatientDesc': 'الوصول إلى السجلات الطبية والمواعيد',
      'roleDoctorDesc': 'إدارة المرضى والجداول الزمنية',
      'roleStudentDesc': 'تتبع التدريب وتقديم التقارير',
      'selectRole': 'اختر دورك',
      'roleSubtitle': 'اختر كيف تريد الوصول إلى المنصة',
      'loginTitle': 'أهلاً بك مجدداً',
      'loginSubtitle': 'سجل الدخول إلى حسابك',
      'emailLabel': 'البريد الإلكتروني',
      'passwordLabel': 'كلمة المرور',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'signIn': 'تسجيل الدخول',
      'signUp': 'إنشاء حساب',
      'dontHaveAccount': 'ليس لديك حساب؟',
      'quickActions': 'إجراءات سريعة',
      'bookAppt': 'حجز موعد',
      'medicalRecords': 'السجلات الطبية',
      'labResults': 'نتائج المختبر',
      'medicalRecordsShort': 'السجلات الطبية',
      'labResultsShort': 'نتائج المختبر',
      'pharmacy': 'الصيدلية',
      'upcomingAppt': 'الموعد القادم',
      'viewDetails': 'عرض التفاصيل',
      'confirmed': 'مؤكد',
      'socialStatusVal': 'متزوج، مهندس',
      'weeklySummary': 'ملخص أسبوعي',
      'avgBP': 'معدل ضغط الدم',
      'entriesRecorded': 'تم تسجيل المدخلات هذا الأسبوع',
      'chatbotTitle': 'المساعد الصحي الذكي',
      'chatbotAlwaysAvailable': 'متاح دائماً',
      'chatbotWelcome': 'مرحباً! أنا مساعدك الصحي الذكي. كيف يمكنني مساعدتك اليوم؟',
      'chatbotTyping': 'المساعد يكتب حالياً...',
      'chatbotInputHint': 'اسأل عن صحتك...',
      'suggestHeadache': 'لدي صداع',
      'suggestBookAppt': 'حجز موعد',
      'suggestLabResults': 'نتائج المختبر',
      'navPatients': 'المرضى',
      'navSchedule': 'الجدول الزمني',
      'doctorInsightsTitle': 'الأبحاث والرؤى الطبية',
      'doctorInsightsSubtitle': 'ابق على اطلاع بأحدث الدراسات السريرية',
      'knowledgeLibraryTitle': 'مكتبة المعرفة',
      'publishResearch': 'نشر بحث',
      'postResearchTitle': 'شارك بحثك الطبي',
      'labelCommunity': 'مجتمع الأطباء',
      'researchSearchHint': 'ابحث في الكتب أو المجلات أو الإرشادات...',
      'trendingTitle': 'رائج وشائع',
      'searchResultsTitle': 'نتائج البحث ({count})',
      'noResultsFound': 'لم يتم العثور على موارد لهذا البحث.',
      'sectAccount': 'الحساب',
      'sectPreferences': 'التفضيلات',
      'sectSupport': 'الدعم',
      'sectAcademicManagement': 'الإدارة الأكاديمية',
      'optPersonalInfo': 'المعلومات الشخصية',
      'subPersonalInfo': 'تعديل بياناتك الشخصية المسجلة',
      'optAcademicManagement': 'الإدارة الأكاديمية',
      'subAcademicManagement': 'عرض تقديمات الطلاب وإدارة المهام المكلفة',
      'sectAppearance': 'المظهر',
      'optEditInfo': 'تعديل المعلومات',
      'optChangePassword': 'تغيير كلمة المرور',
      'optDarkMode': 'الوضع الداكن',
      'optLightMode': 'الوضع الفاتح',
      'optLanguage': 'اللغة',
      'sectHelp': 'المساعدة',
      'optContactSupport': 'دعم المستخدم',
      'optReportIssue': 'الإبلاغ عن مشكلة',
      'actionLogOut': 'تسجيل الخروج',
      'sectSecurityUpdate': 'تحديث الأمان',
      'subSecurityUpdate': 'حافظ على أمان حسابك عن طريق تحديث كلمة المرور بانتظام',
      'labelCurrentPassword': 'كلمة المرور الحالية',
      'labelNewPassword': 'كلمة المرور الجديدة',
      'labelConfirmNewPassword': 'تأكيد كلمة المرور الجديدة',
      'actionUpdatePassword': 'تحديث كلمة المرور',
      'msgPasswordUpdated': 'تم تحديث كلمة المرور بنجاح',
      'errorRequired': 'هذا الحقل مطلوب',
      'errorPasswordShort': 'كلمة المرور قصيرة جداً (6 أحرف على الأقل)',
      'errorPasswordsMismatch': 'كلمات المرور غير متطابقة',
      'optHelpCenter': 'مركز المساعدة',
      'labelDeveloper': 'المطور',
      'labelContactEmail': 'بريد التواصل',
      'optAboutApp': 'عن التطبيق',
      'labelMission': 'مهمتنا',
      'labelCredits': 'اعتمادات المطور',
      'labelVersion': 'الإصدار',
      'tabSyllabus': 'المنهج',
      'tabAssignments': 'الواجبات',
      'tabResources': 'المصادر',
      'sectCourseOverview': 'نظرة عامة على الدورة',
      'sectModules': 'الوحدات',
      'sectUpcoming': 'القادمة',
      'sectPast': 'السابقة',
      'actionContactInstructor': 'اتصل بالمحاضر',
      'msgContactingInstructor': 'جاري الاتصال بالمحاضر...',
      'manageSchedule': 'إدارة الجدول',
      'latestVitals': 'أحدث العلامات الحيوية',
      'doctorPatientListTitle': 'قائمة المرضى الخاصة بك',
      'condHealthy': 'بصحة جيدة',
      'statTotalPatients': 'إجمالي المرضى',
      'statCompletedToday': 'أنجز اليوم',
      'statPendingReviews': 'مراجعات معلقة',
      'statTodaysAppointments': 'مواعيد اليوم',
      'noPatients': 'لا يوجد مرضى حالياً',
      'doctorMyPatientsTitle': 'مرضاي',
      'doctorAddPatientTitle': 'إضافة مريض جديد',
      'labelPatientName': 'اسم المريض',
      'labelAge': 'العمر',
      'labelCondition': 'الحالة المرضية',
      'actionAddPatient': 'إضافة مريض',
      'msgPatientAdded': 'تم إضافة المريض بنجاح',
      'labelLastVisit': 'آخر زيارة',
      'doctorProfileTitle': 'معلومات الملف الشخصي',
      'msgProfileUpdated': 'تم تحديث الملف الشخصي بنجاح',
      'labelPhone': 'الهاتف',
      'labelDOB': 'تاريخ الميلاد',
      'labelSpecialization': 'التخصص',
      'labelLocation': 'الموقع',
      'labelNotSet': 'غير محدد',
      'bpLabel': 'ضغط الدم',
      'bpmLabel': 'نبض',
      'kgLabel': 'كجم',
      'demographics': 'المعلومات الشخصية',
      'bloodType': 'فصيلة الدم',
      'socialStatus': 'الحالة الاجتماعية',
      'chronicDiseases': 'الأمراض المزمنة',
      'healthAlert': 'تنبيه صحي',
      'highBPAlert': 'تنبيه ارتفاع ضغط الدم',
      'highBPMessage': 'خطر: قراءتك الأخيرة كانت {sys}/{dia}. يرجى الراحة واستشارة الطبيب.',
      'confirm': 'تأكيد',
      'cancelAptTitle': 'إلغاء الموعد',
      'cancelAptConfirm': 'هل أنت متأكد أنك تريد إلغاء موعدك مع {doctor} في {date} الساعة {time}؟',
      'errorCancelApt': 'فشل إلغاء الموعد. يرجى المحاولة مرة أخرى.',
      'sampleCoursesSeeded': 'تم إنشاء دورات تجريبية بنجاح!',
      'coursesExistOrFailed': 'الدورات موجودة بالفعل أو فشل الإنشاء.',
      'actionSeedCourses': 'إنشاء دورات تجريبية',
      'bookingTitle': 'حجز موعد',
      'searchDoctor': 'ابحث عن طبيب...',
      'specAll': 'الكل',
      'specCardiology': 'أمراض القلب',
      'specNeurology': 'أمراض الأعصاب',
      'specOphthalmology': 'أمراض العيون',
      'specOrthopedics': 'جراحة العظام',
      'specPediatrics': 'طب الأطفال',
      'labelDoctorCount': 'تم العثور على {count} أطباء',
      'selectDateTime': 'اختر التاريخ والوقت',
      'labelSelectDate': 'اختر التاريخ',
      'labelSelectTime': 'اختر الوقت',
      'confirmAppt': 'تأكيد الموعد',
      'apptSuccessTitle': 'تم حجز الموعد!',
      'apptSuccessDesc': 'تم تحديد موعدك بنجاح. يمكنك رؤيته في لوحة التحكم الخاصة بك.',
      'labelDoctorInfo': 'معلومات الطبيب',
      'labelDate': 'التاريخ',
      'labelTime': 'الوقت',
      'labelDone': 'تم',
      'callMyDoctors': 'الاتصال بأطبائي',
      'healthUpdate': 'تحديث صحي',
      'labPendingReview': '{count} تقارير مختبر قيد المراجعة',
      'tabOverview': 'نظرة عامة',
      'tabVitals': 'العلامات الحيوية',
      'labelHeartRate': 'ضربات القلب',
      'labelBloodPressure': 'ضغط الدم',
      'labelBloodGlucose': 'سكر الدم',
      'unitBpm': 'نبضة/دقيقة',
      'unitMmHg': 'ملم زئبقي',
      'unitLbs': 'رطل',
      'unitMgDl': 'ملجم/ديسيلتر',
      'labelDiagnosedDate': 'تاريخ التشخيص',
      'quickAddVitals': 'إضافة سريعة للعلامات الحيوية',
      'labelBPTrend': 'اتجاه ضغط الدم',
      'labelHRTrend': 'اتجاه ضربات القلب',
      'labelWeightTrend': 'اتجاه الوزن',
      'labelBGTrend': 'اتجاه سكر الدم',
      'labelSystolic': 'الانقباضي',
      'labelDiastolic': 'الانبساطي',
      'save': 'حفظ',
      'msgSuccess': 'تم الحفظ بنجاح',
      'labelRecentHistory': 'السجل الأخير',
      'labelTreatingPhysician': 'الطبيب المعالج',
      'labelManagementPlan': 'خطة العلاج',
      'labelLastUpdated': 'آخر تحديث',
      'labResultsTitle': 'نتائج المختبر',
      'labTrends': 'اتجاهات سكر الدم',
      'labTrendsDesc': 'مستخرجة من تقارير المختبر الخاصة بك باستخدام Smart OCR.',
      'recentLabReports': 'تقارير المختبر الأخيرة',
      'reportFrom': 'تقرير من تاريخ {date}',
      'extractedGlucose': 'الجلوكوز المستخرج: {value} ملجم/ديسيلتر',
      'noLabResults': 'لا توجد نتائج مختبر متاحة',
      'close': 'إغلاق',
      'settingsTitle': 'الإعدادات',
      'noMessages': 'لا توجد رسائل',
      'labelYears': 'سنوات',
      'labelNone': 'لا يوجد',
      'labelSingle': 'أعزب',
      'profileTitle': 'ملف المريض',
      'labelPatient': 'مريض',
      'unitYears': 'سنة',
      'labelBlood': 'فصيلة الدم',
      'labelNotAvailable': 'غير متوفر',
      'actionLogout': 'تسجيل الخروج',
      'actionEditMedicalProfile': 'تعديل الملف الطبي',
      'actionSave': 'حفظ',
      'sectPersonalInfo': 'المعلومات الشخصية',
      'sectChronicConditions': 'الأمراض المزمنة',
      'labelHeight': 'الطول',
      'labelWeight': 'الوزن',
      'labelDOBShort': 'تاريخ الميلاد',
      'labelSocialStatus': 'الحالة الاجتماعية',
      'msgNoConditions': 'لم يتم تسجيل أي حالات',
      'actionAddCondition': 'إضافة حالة',
      'labelConditionName': 'اسم الحالة',
      'labelStatusHint': 'الحالة الحالية (مثلاً: مستقرة)',
      'msgMedicalProfileUpdated': 'تم تحديث الملف الطبي بنجاح',
      'labelStatus': 'الحالة:',
      'actionAdd': 'إضافة',
      'labelUnknownUser': 'مستخدم غير معروف',
      'doctorScheduleTitle': 'جدول المواعيد',
      'tabUpcoming': 'القادمة',
      'tabCompleted': 'المكتملة',
      'tabCancelled': 'الملغاة',
      'msgNoAppointments': 'لا توجد مواعيد',
      'actionJoin': 'انضمام',
      'actionCancel': 'إلغاء',
      'actionConfirm': 'تأكيد',
      'msgAppointmentConfirmed': 'تم تأكيد الموعد بنجاح',
      'msgAppointmentCancelled': 'تم إلغاء الموعد بنجاح',
      'labelUnknownPatient': 'مريض غير معروف',
      'labelVisit': 'زيارة',
      'labelAt': 'في',
      'errorLoadAppointments': 'فشل تحميل المواعيد',
      'errorUpdateStatus': 'فشل تحديث حالة الموعد',
      'labelManageAvailability': 'إدارة المواعيد',
      'titleCases': 'المكتبة',
      'msgNoDoctorsAvailable': 'لا يوجد أطباء متاحون في قاعدة البيانات.',
      'hintSelectDoctor': 'اختر طبيباً',
      'msgTitleDoctorRequired': 'العنوان والطبيب مطلوبان',
      'msgReportSubmitError': 'فشل تقديم التقرير',
      'msgNoReports': 'لم يتم تقديم أي تقارير بعد.',
      'msgSubmittedAt': 'تم التقديم في: {date}\nإلى معرف الطبيب: {id}',
      'msgNoTasks': 'لا توجد مهام مكلفة بعد.',
      'msgNoCoursesEnrolled': 'لم يتم التسجيل في أي دورات بعد.',
      'labelSupervisorDoctor': 'المشرف (طبيب)',
      'labelFileAttached': 'تم إرفاق الملف',
      'errorLoadReports': 'خطأ في تحميل التقارير',
      'universityTools': 'أدوات الجامعة',
      'toolHospital': 'المستشفى',
      'toolDoctors': 'الأطباء',
      'toolReports': 'التقارير',
      'toolTasks': 'المهام',
      'navCourses': 'دوراتي',
      'navCases': 'الحالات',
      'currentLevel': 'المستوى الحالي',
      'year4': 'السنة الرابعة',
      'modeClinical': 'سريري',
      'pendingAssignment': 'مهمة قيد الانتظار',
      'assignmentDesc': 'مستحقة هذا الأسبوع',
      'actionViewCaseStudy': 'عرض دراسة الحالة',
      'titleFindDoctor': 'ابحث عن طبيب',
      'labelBy': 'بواسطة ',
      'labelAttendance': 'الحضور',
      'titleMyCourses': 'دوراتي',
      'labelSemester1_2026': 'الفصل الدراسي الأول، 2026',
      'labelResumeLearning': 'مواصلة التعلم',
      'labelInProgress': 'قيد التقدم',
      'labelGrade': 'الدرجة: {grade}',
      'labelProgress': 'التقدم',
      'labelNext': 'التالي: {time}',
      'actionViewDetails': 'عرض التفاصيل',
      'titleJoinNewCourse': 'الانضمام لدورة جديدة',
      'labelNoAvailableCourses': 'لا توجد دورات جديدة متاحة للانضمام.',
      'actionJoinCourse': 'الانضمام للدورة',
      'messageJoinSuccess': 'تم الانضمام للدورة بنجاح!',
      'messageJoinError': 'فشل في الانضمام للدورة.',
      'labelCaseStudy': 'دراسة حالة #{id}',
      'labelCardiology': 'أمراض القلب',
      'titleCaseStudy': 'مرض السكري من النوع 1 المعقد',
      'labelCaseDuration': 'ساعتان',
      'labelPriority': 'أولوية عالية',
      'tabClinical': 'سريري',
      'tabLabs': 'مختبر',
      'tabDiagnosis': 'التشخيص',
      'labelChiefComplaint': 'الشكوى الرئيسية',
      'labelPatientDemographics': 'البيانات الديموغرافية للمريض',
      'labelInitialVitals': 'العلامات الحيوية الأولية',
      'labelLearningObjectives': 'الأهداف التعليمية',
      'actionCompleteCase': 'إكمال الحالة',
      'actionTakeNotes': 'تدوين الملاحظات',
    },
    'ku': {
      'appName': 'MyChart',
      'welcome': 'بەخێربێیت',
      'seeAll': 'بینینی هەموو',
      'back': 'گەڕانەوە',
      'next': 'دواتر',
      'getStarted': 'دەستپێبکە',
      'navHome': 'سەرەکی',
      'navMessages': 'نامەکان',
      'navChatbot': 'یاریدەدەری زیرەک',
      'navSettings': 'ڕێکخستنەکان',
      'rolePatient': 'نەخۆش',
      'roleDoctor': 'پزیشک',
      'roleStudent': 'خوێندکار',
      'rolePatientDesc': 'دەستگەیشتن بە تۆمارە پزیشکییەکان و کاتەکان',
      'roleDoctorDesc': 'بەڕێوەبردنی نەخۆشەکان و کاتەکان',
      'roleStudentDesc': 'شوێنکەوتنی مەشقەکان و ناردنی ڕاپۆرتەکان',
      'selectRole': 'ڕۆڵەکەت هەڵبژێرە',
      'roleSubtitle': 'شێوازی چوونە ناو سیستمەکە هەڵبژێرە',
      'loginTitle': 'بەخێربێیتەوە',
      'loginSubtitle': 'بچۆ ناو هەژمارەکەت',
      'emailLabel': 'ئیمەیڵ',
      'passwordLabel': 'وشەی نهێنی',
      'forgotPassword': 'وشەی نهێنیت لەبیر کردووە؟',
      'signIn': 'چوونە ژوورەوە',
      'signUp': 'دروستکردنی هەژمار',
      'dontHaveAccount': 'هەژمارت نییە؟',
      'quickActions': 'کردارە خێراکان',
      'bookAppt': 'حجزی کات',
      'medicalRecords': 'تۆمارە پزیشکییەکان',
      'labResults': 'ئەنجامی تاقیگە',
      'pharmacy': 'دەرمانخانە',
      'upcomingAppt': 'کاتی داهاتوو',
      'viewDetails': 'بینینی وردەکاری',
      'confirmed': 'پەسەندکراوە',
      'socialStatusVal': 'هاوسەرگیر، ئەندازیار',
      'weeklySummary': 'کورتەی هەفتانە',
      'avgBP': 'تێکڕای پەستانی خوێن',
      'entriesRecorded': 'تۆمارەکان لەم هەفتەیەدا',
      'chatbotTitle': 'عەقڵی دەستکردی تەندروستی',
      'chatbotAlwaysAvailable': 'بەردەوام ئامادەیە',
      'chatbotWelcome': 'سڵاو! من یاریدەدەری تەندروستی تۆم. چۆن دەتوانم ئەمڕۆ هاوکارت بم؟',
      'chatbotTyping': 'یاریدەدەرەکە خەریکی نووسینە...',
      'chatbotInputHint': 'پرسیار دەربارەی تەندروستیت بکە...',
      'suggestHeadache': 'سەرم دێشێت',
      'suggestBookAppt': 'ژوان دیاری بکە',
      'suggestLabResults': 'ئەنجامی پشکنین',
      'navPatients': 'نەخۆشەکان',
      'navSchedule': 'خشتەی کاتەکان',
      'doctorInsightsTitle': 'توێژینەوە و تێڕوانینە پزیشکییەکان',
      'doctorInsightsSubtitle': 'ئاگارداربە لە نوێترین توێژینەوە پزیشکییەکان',
      'knowledgeLibraryTitle': 'کتێبخانەی زانیاری',
      'publishResearch': 'بڵاوکردنەوەی توێژینەوە',
      'postResearchTitle': 'توێژینەوەکەت بڵاوبکەرەوە',
      'labelCommunity': 'کۆمەڵگەی پزیشکان',
      'researchSearchHint': 'گەڕان بۆ کتێب یان گۆڤار یان ڕێساکان...',
      'trendingTitle': 'باو و ناسراو',
      'searchResultsTitle': 'ئەنجامەکانی گەڕان ({count})',
      'noResultsFound': 'هیچ سەرچاوەیەک بۆ ئەم گەڕانە نەدۆزرایەوە.',
      'sectAccount': 'هەژمار',
      'sectPreferences': 'پێدانی ئەولەویەتەکان',
      'sectSupport': 'پشتیوانی',
      'sectAcademicManagement': 'بەڕێوەبردنی ئەکادیمی',
      'optPersonalInfo': 'زانیارییە کەسییەکان',
      'subPersonalInfo': 'دەستکاری کردنی زانیارییە کەسییە تۆمارکراوەکانت بکە',
      'optAcademicManagement': 'بەڕێوەبردنی ئەکادیمی',
      'subAcademicManagement': 'بینینی نێردراوەکانی خوێندکاران و بەڕێوەبردنی ئەرکەکان',
      'sectAppearance': 'ڕووکار',
      'optEditInfo': 'گۆڕینی زانیارییەکان',
      'optChangePassword': 'گۆڕینی وشەی نهێنی',
      'optDarkMode': 'باری تاریک',
      'optLightMode': 'باری ڕووناک',
      'optLanguage': 'زمان',
      'sectHelp': 'یارمەتی',
      'optContactSupport': 'پەیوەندی بە پشتگیری',
      'optReportIssue': 'ڕاپۆرتکردنی کێشەیەک',
      'actionLogOut': 'چوونەدەرەوە',
      'sectSecurityUpdate': 'نوێکردنەوەی ئاسایش',
      'subSecurityUpdate': 'هەژمارەکەت بە پارێزراوی بهێڵەرەوە بە نوێکردنەوەی وشەی نهێنیت بە شێوەیەکی دەوری',
      'labelCurrentPassword': 'وشەی نهێنی ئێستا',
      'labelNewPassword': 'وشەی نهێنی نوێ',
      'labelConfirmNewPassword': 'دڵنیابوونەوە لە وشەی نهێنی نوێ',
      'actionUpdatePassword': 'نوێکردنەوەی وشەی نهێنی',
      'msgPasswordUpdated': 'وشەی نهێنی بە سەرکەوتوویی نوێکرایەوە',
      'errorRequired': 'پێویستە ئەم خانەیە پڕبکرێتەوە',
      'errorPasswordShort': 'وشەی نهێنی زۆر کورتە (کەمترین ٦ پیت)',
      'errorPasswordsMismatch': 'وشەی نهێنییەکان وەک یەک نین',
      'optHelpCenter': 'سەنتەری یارمەتی',
      'labelDeveloper': 'گەشەپێدەر',
      'labelContactEmail': 'ئیمەیڵی پەیوەندی',
      'optAboutApp': 'دەربارەی ئەپڵیکەیشن',
      'labelMission': 'ئەرکی ئێمە',
      'labelCredits': 'متمانەی گەشەپێدەر',
      'labelVersion': 'وەشان',
      'tabSyllabus': 'پڕۆگرام',
      'tabAssignments': 'ئەرکەکان',
      'tabResources': 'سەرچاوەکان',
      'sectCourseOverview': 'کورتەی کۆرس',
      'sectModules': 'مۆدیوولەکان',
      'sectUpcoming': 'داهاتوو',
      'sectPast': 'ڕابردوو',
      'actionContactInstructor': 'پەیوەندی بە مامۆستاوە بکە',
      'msgContactingInstructor': 'پەیوەندی بە مامۆستاوە دەکرێت...',
      'manageSchedule': 'بەڕێوەبردنی خشتە',
      'latestVitals': 'دواهەمین نیشانە گرنگەکان',
      'doctorPatientListTitle': 'لیستی نەخۆشەکانت',
      'condHealthy': 'تەندروستی باشە',
      'statTotalPatients': 'کۆی گشتی نەخۆشەکان',
      'statCompletedToday': 'تەواوکراوی ئەمڕۆ',
      'statPendingReviews': 'پێداچوونەوە هەڵپەسێردراوەکان',
      'statTodaysAppointments': 'ژوانەکانی ئەمڕۆ',
      'noPatients': 'هیچ نەخۆشێک نییە',
      'doctorMyPatientsTitle': 'نەخۆشەکانم',
      'doctorAddPatientTitle': 'زیادکردنی نەخۆشی نوێ',
      'labelPatientName': 'ناوی نەخۆش',
      'labelAge': 'تەمەن',
      'labelCondition': 'باری تەندروستی',
      'actionAddPatient': 'زیادکردنی نەخۆش',
      'msgPatientAdded': 'نەخۆشەکە بە سەرکەوتوویی زیادکرا',
      'labelLastVisit': 'دوا سەردان',
      'doctorProfileTitle': 'زانیاری دۆسیەی کەسی',
      'msgProfileUpdated': 'دۆسیەی کەسی بە سەرکەوتوویی نوێکرایەوە',
      'labelPhone': 'مۆبایل',
      'labelDOB': 'ڕێکەوتی لەدایکبوون',
      'labelSpecialization': 'پسپۆڕی',
      'labelLocation': 'شوێن',
      'labelNotSet': 'دیاری نەکراوە',
      'bpLabel': 'پەستانی خوێن',
      'bpmLabel': 'لێدانی دڵ',
      'kgLabel': 'کیلۆگرام',
      'healthAlert': 'ئاگادارکردنەوەی تەندروستی',
      'highBPAlert': 'ئاگادارکردنەوەی بەرزی پەستانی خوێن',
      'highBPMessage': 'مەترسی: دوایین قراءتت {sys}/{dia} بوو. تکایە پشوو بدە و پەیوەندی بە پزیشکەکەتەوە بکە.',
      'confirm': 'دوپاتکردنەوە',
      'cancelAptTitle': 'هەڵوەشاندنەوەی ژوان',
      'cancelAptConfirm': 'ئایا دڵنیایت کە دەتەوێت ژوانەکەت لەگەڵ {doctor} لە {date} کاتژمێر {time} هەڵبووەشێنیتەوە؟',
      'errorCancelApt': 'هەڵوەشاندنەوەی ژوانەکە سەرکەوتوو نەبوو. تکایە دووبارە هەوڵ بدەرەوە.',
      'sampleCoursesSeeded': 'کۆرسە نموونەییەکان بە سەرکەوتوویی دروستکران!',
      'coursesExistOrFailed': 'کۆرسەکان پێشتر هەبوون یان دروستکردنیان سەرکەوتوو نەبوو.',
      'actionSeedCourses': 'دروستکردنی کۆرسی نموونەیی',
      'bookingTitle': 'حجزی کات',
      'searchDoctor': 'بگەڕێ بۆ پزیشکێک...',
      'specAll': 'هەمووی',
      'specCardiology': 'نەخۆشییەکانی دڵ',
      'specNeurology': 'نەخۆشییەکانی مێشک و دەمار',
      'specOphthalmology': 'نەخۆشییەکانی چاو',
      'specOrthopedics': 'نەشتەرگەری ئێسک',
      'specPediatrics': 'پزیشکی منداڵان',
      'labelDoctorCount': '{count} پزیشک دۆزرانەوە',
      'selectDateTime': 'بەروار و کات هەڵبژێرە',
      'labelSelectDate': 'بەروار هەڵبژێرە',
      'labelSelectTime': 'کات هەڵبژێرە',
      'confirmAppt': 'دوپاتکردنەوەی ژوان',
      'apptSuccessTitle': 'ژوانەکە تۆمارکرا!',
      'apptSuccessDesc': 'ژوانەکەت بە سەرکەوتوویی دیاریکرا. دەتوانیت لە داشبۆردەکەت بیبینیت.',
      'labelDoctorInfo': 'زانیاری پزیشک',
      'labelDate': 'بەروار',
      'labelTime': 'کات',
      'labelDone': 'تەواو',
      'callMyDoctors': 'پەیوەندی بە پزیشکەکانمەوە بکە',
      'healthUpdate': 'نوێکردنەوەی تەندروستی',
      'labPendingReview': '{count} پشکنین قيد پێداچوونەوەیە',
      'tabOverview': 'کورتەی گشتی',
      'tabVitals': 'نیشانە گرنگەکان',
      'labelHeartRate': 'لێدانی دڵ',
      'labelBloodPressure': 'پەستانی خوێن',
      'labelBloodGlucose': 'ڕێژەی شەکر',
      'unitBpm': 'لێدان/خوولەک',
      'unitMmHg': 'ملم جەیوە',
      'unitLbs': 'پاوند',
      'unitMgDl': 'mg/dL',
      'labelDiagnosedDate': 'دەستنیشانکراوە لە',
      'quickAddVitals': 'زیادکردنی خێرای نیشانەکان',
      'labelBPTrend': 'ئاڕاستەی پەستانی خوێن',
      'labelHRTrend': 'ئاڕاستەی لێدانی دڵ',
      'labelWeightTrend': 'ئاڕاستەی کێش',
      'labelBGTrend': 'ئاڕاستەی ڕێژەی شەکر',
      'labelSystolic': 'پەستانی بەرز (سیستۆلیک)',
      'labelDiastolic': 'پەستانی نزم (دیاستۆلیک)',
      'save': 'پاشەکەوت بکە',
      'msgSuccess': 'نیشانەکان بە سەرکەوتوویی تۆمارکران',
      'labelRecentHistory': 'مێژووی دوایی',
      'labelTreatingPhysician': 'پزیشکی چارەسەرکەر',
      'labelManagementPlan': 'پلانی بەڕێوەبردن',
      'labelLastUpdated': 'دوا نوێکردنەوە',
      'labelYears': 'ساڵ',
      'labelNone': 'نییە',
      'labelSingle': 'تەڵەب',
      'profileTitle': 'دۆسیەی کەسی',
      'labelPatient': 'نەخۆش',
      'unitYears': 'ساڵ',
      'labelBlood': 'جۆری خوێن',
      'labelNotAvailable': 'بەردەست نییە',
      'actionLogout': 'چوونەدەرەوە',
      'actionEditMedicalProfile': 'دەستکاری دۆسیەی پزیشکی بکە',
      'actionSave': 'پاشەکەوت بکە',
      'sectPersonalInfo': 'زانیارییە کەسییەکان',
      'sectChronicConditions': 'نەخۆشییە درێژخایەنەکان',
      'labelHeight': 'باڵا',
      'labelWeight': 'کێش',
      'labelDOBShort': 'ڕێکەوتی لەدایکبوون',
      'labelSocialStatus': 'باری کۆمەڵایەتی',
      'msgNoConditions': 'هیچ نەخۆشییەک تۆمار نەکراوە',
      'actionAddCondition': 'زیادکردنی نەخۆشی',
      'labelConditionName': 'ناوی نەخۆشی',
      'labelStatusHint': 'باری ئێستا (بۆ نموونە: جێگیر)',
      'msgMedicalProfileUpdated': 'دۆسیەی پزیشکی بە سەرکەوتوویی نوێکرایەوە',
      'labelStatus': 'بار:',
      'actionAdd': 'زیاد بکە',
      'labelUnknownUser': 'بەکارهێنەری نەناسراو',
      'labelEmailAddress': 'ئیمەیڵ',
      'labelPhoneNumber': 'ژمارەی مۆبایل',
      'demographics': 'زانیاری کەسی',
      'bloodType': 'جۆری خوێن',
      'socialStatus': 'باری کۆمەڵایەتی',
      'chronicDiseases': 'نەخۆشییە درێژخایەنەکان',
      'medicalRecordsShort': 'تۆمارە پزیشکییەکان',
      'labResultsShort': 'ئەنجامی تاقیگە',
      'pharmacyShort': 'دەرمانخانە',
      'settingsTitle': 'ڕێکخستنەکان',
      'noMessages': 'هیچ نامەیەک نییە',
      'labResultsTitle': 'ئەنجامی تاقیگە',
      'labTrends': 'ئاڕاستەی ڕێژەی شەکر',
      'labTrendsDesc': 'لە پشکنینەکانتەوە دەرگیراوە بە بەکارهێنانی OCR زیرەک.',
      'recentLabReports': 'پشکنینە دواییەکان',
      'reportFrom': 'پشکنینی بەرواری {date}',
      'extractedGlucose': 'ڕێژەی شەکری دەرگیراو: {value} mg/dL',
      'noLabResults': 'هیچ ئەنجامێکی تاقیگە بەردەست نییە',
      'close': 'داخستن',
      'doctorScheduleTitle': 'خشتەی ژوانەکان',
      'tabUpcoming': 'داهاتوو',
      'tabCompleted': 'تەواوکراو',
      'tabCancelled': 'هەڵوەشێنراوە',
      'msgNoAppointments': 'هیچ ژوانێک نییە',
      'actionJoin': 'بەشداری بکە',
      'actionCancel': 'هەڵوەشاندنەوە',
      'actionConfirm': 'دووپاتکردنەوە',
      'msgAppointmentConfirmed': 'ژوانەکە بە سەرکەوتوویی دووپاتکرایەوە',
      'msgAppointmentCancelled': 'ژوانەکە بە سەرکەوتوویی هەڵوەشێنرایەوە',
      'labelUnknownPatient': 'نەخۆشی نەناسراو',
      'labelVisit': 'سەردان',
      'labelAt': 'لە',
      'errorLoadAppointments': 'بارکردنی ژوانەکان سەرکەوتوو نەبوو',
      'errorUpdateStatus': 'گۆڕینی باری ژوانەکە سەرکەوتوو نەبوو',
      'labelManageAvailability': 'بەڕێوەبردنی بەردەستبوون',
      'titleCases': 'کتێبخانە',
      'msgNoDoctorsAvailable': 'هیچ پزیشکێک لە داتابەیسدا بەردەست نییە.',
      'hintSelectDoctor': 'پزیشکێک هەڵبژێرە',
      'msgTitleDoctorRequired': 'ناونیشان و پزیشک پێویستن',
      'msgReportSubmitError': 'ناردنی ڕاپۆرتەکە سەرکەوتوو نەبوو',
      'msgNoReports': 'هێشتا هیچ ڕاپۆرتێک نەنێردراوە.',
      'msgSubmittedAt': 'نێردراوە لە: {date}\nبۆ ناسنامەی پزیشک: {id}',
      'msgNoTasks': 'هێشتا هیچ ئەرکێک دیاری نەکراوە.',
      'msgNoCoursesEnrolled': 'هێشتا لە هیچ کۆرسێکدا ناوت تۆمار نەکراوە.',
      'labelSupervisorDoctor': 'سەرپەرشتیار (پزیشک)',
      'labelFileAttached': 'فایلەکە هاوپێچ کرا',
      'errorLoadReports': 'هەڵە لە بارکردنی ڕاپۆرتەکاندا',
      'universityTools': 'ئامرازەکانی زانکۆ',
      'toolHospital': 'نەخۆشخانە',
      'toolDoctors': 'پزیشکەکان',
      'toolReports': 'ڕاپۆرتەکان',
      'toolTasks': 'ئەرکەکان',
      'navCourses': 'کۆرسەکانم',
      'navCases': 'حاڵەتەکان',
      'currentLevel': 'ئاستی ئێستا',
      'year4': 'ساڵی چوارەم',
      'modeClinical': 'سەرینی',
      'pendingAssignment': 'ئەرکی هەڵپەسێردراو',
      'assignmentDesc': 'لەم هەفتەیەدا دەبێت تەواو بکرێت',
      'actionViewCaseStudy': 'بینینی حاڵەتەکە',
      'titleFindDoctor': 'پزیشکێک بدۆزەرەوە',
      'labelBy': 'لە لایەن ',
      'labelAttendance': 'ئامادەبوون',
      'titleMyCourses': 'کۆرسەکانم',
      'labelSemester1_2026': 'وەرزی یەکەم، 2026',
      'labelResumeLearning': 'بەردەوامبوون لە فێربوون',
      'labelInProgress': 'لە بەردەوامبووندایە',
      'labelGrade': 'نمرە: {grade}',
      'labelProgress': 'پێشکەوتن',
      'labelNext': 'داهاتوو: {time}',
      'actionViewDetails': 'بینینی وردەکارییەکان',
      'titleJoinNewCourse': 'بەشداریکردن لە کۆرسی نوێ',
      'labelNoAvailableCourses': 'هیچ کۆرسێکی نوێ بەردەست نییە بۆ بەشداریکردن.',
      'actionJoinCourse': 'بەشداریکردن',
      'messageJoinSuccess': 'بە سەرکەوتوویی بەشداریت لە کۆرسەکە کرد!',
      'messageJoinError': 'بەشداریکردن لە کۆرسەکە سەرکەوتوو نەبوو.',
      'labelCaseStudy': 'لێکۆڵینەوەی کەیس #{id}',
      'labelCardiology': 'نەخۆشییەکانی دڵ',
      'titleCaseStudy': 'نەخۆشی شەکرەی جۆری 1ی ئاڵۆز',
      'labelCaseDuration': 'دوو کاتژمێر',
      'labelPriority': 'پێشینەی بەرز',
      'tabClinical': 'سەرینی',
      'tabLabs': 'تاقیگە',
      'tabDiagnosis': 'دەستنیشانکردن',
      'labelChiefComplaint': 'سکاڵای سەرەکی',
      'labelPatientDemographics': 'زانیاری نەخۆش',
      'labelInitialVitals': 'نیشانە زیندووە سەرەتاییەکان',
      'labelLearningObjectives': 'ئامانجەکانی فێربوون',
      'actionCompleteCase': 'تەواوکردنی کەیس',
      'actionTakeNotes': 'تێبینی وەرگرتن',
    },
  };

  static String get(String key, String lang) {
    return _localizedValues[lang]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}
