
class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appName': 'MyChart',
      'welcome': 'Welcome',
      'back': 'Back',
      'next': 'Next',
      'getStarted': 'Get Started',
      'studentIdLabel': 'University Email',
      'studentIdHint': 'e.g., username@cihanuniversity.edu.iq',
      'studentPasswordHint': 'Enter your password',
      'studentEmailLoginHint': 'Use your university email to sign in',
      'continueAsGuest': 'Continue as Guest',
      'appTagline': 'Your Health, In Your Hands',
      'featureRecords': 'Records',
      'featureAppointments': 'Appointments',
      'featureMessages': 'Messages',
      'featureHealth': 'Health',
      'navHome': 'Home',
      'navMessages': 'Messages',
      'navChatbot': 'Chatbot AI',
      'navSettings': 'Settings',
      'selectRole': 'Choose Your Role',
      'roleSubtitle': 'Select how you want to access the platform',
      'rolePatient': 'Patient',
      'rolePatientDesc': 'Access medical records & appointments',
      'roleDoctor': 'Doctor',
      'roleDoctorDesc': 'Manage patients & schedules',
      'roleStudent': 'Student',
      'roleStudentDesc': 'Track training & submit reports',
      'universityTools': 'University Tools',
      'seeAll': 'See All',
      'toolHospital': 'Hospital',
      'toolDoctors': 'Doctors',
      'toolReports': 'Reports',
      'toolTasks': 'Tasks',
      'pendingAssignment': 'Pending Assignment',
      'assignmentDesc': 'Submit your Clinical Pathology report by 5:00 PM today.',
      'currentLevel': 'Current Level',
      'year4': 'Year 4',
      'modeClinical': 'Clinical',
      'gpaLabel': 'GPA: {value}',
      'idLabel': 'ID: {value}',
      'navCourses': 'My Courses',
      'navCases': 'Cases',
      'commonCases': 'Common Cases',
      'caseStudyTitle': 'Case Study',
      'hospitalInfo': 'Hospital Info',
      'hospitalName': 'Grand City University Hospital',
      'hospitalAddress': '123 Medical Center Blvd, Cityville',
      'labelDepartments': 'Departments',
      'labelBeds': 'Beds',
      'aboutUs': 'About Us',
      'hospitalDesc': 'Grand City University Hospital is a premier teaching institution dedicated to providing world-class patient care and educating the next generation of healthcare professionals.',
      'closeInfo': 'Close Info',
      'studentName': 'Alex Thompson',
      'titleJoinNewCourse': 'Join New Course',
      'labelNoAvailableCourses': 'No new courses available to join.',
      'actionJoinCourse': 'Join Course',
      'messageJoinSuccess': 'Successfully joined the course!',
      'messageJoinError': 'Failed to join course.',
      'loginTitle': 'Welcome Back',
      'loginSubtitle': 'Sign in to your account',
      'emailLabel': 'Email Address',
      'passwordLabel': 'Password',
      'emailHint': 'Enter your email',
      'passwordHint': 'Enter your password',
      'forgotPassword': 'Forgot Password?',
      'signIn': 'Sign In',
      'orSignInWith': 'Or sign in with',
      'dontHaveAccount': 'Don\'t have an account?',
      'signUp': 'Sign Up',
      'forgotPasswordTitle': 'Reset Password',
      'forgotPasswordSubtitle': 'Enter your credentials to recover your account',
      'sendResetLink': 'Send Reset Link',
      'checkEmail': 'Check your email for instructions',
      'backToLogin': 'Back to Login',
      'identifierLabel': 'Student ID / Email',
      'doctorIdentifierLabel': 'Sheet ID / Email',
      'verificationTitle': 'Verify Code',
      'verificationSubtitle': 'Enter the 6-digit code sent to your email',
      'verifyControl': 'Verify',
      'titleProfile': 'My Profile',
      'labelEmailAddress': 'Email Address',
      'labelPhoneNumber': 'Phone Number',
      'actionEditProfile': 'Edit Profile',
      'gpa': 'GPA',
      'studentId': 'STUDENT ID',
      'labelSubmitReport': 'Submit Report',
      'labelHistory': 'View Submitted Reports',
      'labelReportTitle': 'Report Title',
      'hintReportTitle': 'e.g., Clinical Pathology Report',
      'labelReportDesc': 'Description',
      'hintReportDesc': 'Brief description of your report...',
      'labelAttachFile': 'Attach File',
      'msgFileFormat': 'PDF, DOC, DOCX (Max 10MB)',
      'actionBrowse': 'Browse',
      'actionSubmit': 'Submit',
      'msgReportSubmitted': 'Report submitted successfully!',
      'titleSubmittedReports': 'Submitted Reports',
      'titleAssignments': 'Assignments',
      'labelDue': 'Due: {date}',
      'actionUploadAssignment': 'Upload New Assignment',
      'descUploadAssignment': 'Submit extra credit work',
      'actionView': 'View',
      'titleMarkAttendance': 'Mark Attendance',
      'descScanQR': 'Scan the QR code in your classroom or clinic to mark your attendance.',
      'actionScanQR': 'Scan QR Code',
      'msgAttendanceMarked': 'Attendance marked successfully!',
      'labelAttendance': 'Attendance',
      'resendCode': 'Resend Code',
      'newPasswordTitle': 'New Password',
      'newPasswordSubtitle': 'Set a strong password for your account',
      'newPasswordLabel': 'New Password',
      'confirmNewPasswordLabel': 'Confirm New Password',
      'newPasswordHint': 'Min. 6 characters',
      'resetSuccess': 'Password changed successfully',
      'passwordMismatch': 'Passwords do not match',
      'signUpTitle': 'Create Account',
      'signUpSubtitle': 'Start your health journey today',
      'fullNameLabel': 'Full Name',
      'phoneLabel': 'Phone Number',
      'confirmPasswordLabel': 'Confirm Password',
      'fullNameHint': 'Enter your full name',
      'phoneHint': 'Enter your phone number',
      'confirmPasswordHint': 'Re-enter your password',
      'alreadyHaveAccount': 'Already have an account?',
      'patientInfo': 'Patient Information',
      'details': 'Details',
      'demographics': 'Demographics',
      'bloodType': 'Blood Type',
      'chronicDiseases': 'Chronic Diseases',
      'quickActions': 'Quick Actions',
      'bookAppt': 'Book Appointment',
      'medicalRecords': 'Medical Records',
      'labResults': 'Lab Results',
      'pharmacy': 'Pharmacy',
      'upcomingAppt': 'Upcoming Appointment',
      'viewDetails': 'View Details',
      'confirmed': 'Confirmed',
      'allResults': 'All Results',
      'socialStatus': 'Social Status',
      'socialStatusVal': 'Married, Engineer',
      'ageVal': 'Female, 34 yrs',
      'medicalRecordsShort': 'Med Records',
      'pharmacyShort': 'Pharmacy',
      'labResultsShort': 'Lab Results',
      'studentEmailError': 'Students must use a university email (@cihanuniversity.edu.iq)',
      'navPatients': 'Patients',
      'navSchedule': 'Schedule',
      'doctorPatientListTitle': 'Your Patient List',
      'doctorInsightsTitle': 'Medical Research & Insights',
      'doctorInsightsSubtitle': 'Stay updated with the latest clinical studies',
      'statTotalPatients': 'Total Patients',
      'statCompletedToday': 'Completed Today',
      'statPendingReviews': 'Pending Reviews',
      'statTodaysAppointments': 'Today\'s Appointments',
      'doctorMyPatientsTitle': 'My Patients',
      'doctorAddPatientTitle': 'Add New Patient',
      'labelPatientName': 'Patient Name',
      'labelAge': 'Age',
      'labelCondition': 'Condition',
      'actionAddPatient': 'Add Patient',
      'msgPatientAdded': 'Patient added successfully',
      'labelLastVisit': 'Last visit',
      'doctorScheduleTitle': 'Schedule',
      'tabUpcoming': 'Upcoming',
      'tabCompleted': 'Completed',
      'tabCancelled': 'Cancelled',
      'msgNoAppointments': 'No appointments found',
      'actionJoin': 'Join',
      'actionConfirm': 'Confirm',
      'msgAppointmentConfirmed': 'Appointment confirmed',
      'msgAppointmentCancelled': 'Appointment cancelled',
      'labelDuration': 'Duration',
      'doctorProfileTitle': 'Profile Info',
      'msgProfileUpdated': 'Profile updated successfully',
      'labelPhone': 'Phone',
      'labelDOB': 'Date of Birth',
      'labelSpecialization': 'Specialization',
      'labelLocation': 'Location',
      'labelNotSet': 'Not set',
      'publishResearch': 'Publish Research',
      'postResearchTitle': 'Share Your Research',
      'labelCommunity': 'Doctor Community',
      'researchSearchHint': 'Search books, journals, or guidelines...',
      'trendingTitle': 'Trending & Popular',
      'knowledgeLibraryTitle': 'Knowledge Library',
      'searchResultsTitle': 'Search Results ({count})',
      'noResultsFound': 'No resources found for this search.',
    },
    'ar': {
      'appName': 'MyChart',
      'welcome': 'مرحباً',
      'seeAll': 'عرض الكل',
      'doctorInsightsTitle': 'الأبحاث والرؤى الطبية',
      'doctorInsightsSubtitle': 'ابق على اطلاع بأحدث الدراسات السريرية',
      'knowledgeLibraryTitle': 'مكتبة المعرفة',
      'publishResearch': 'نشر بحث',
      'postResearchTitle': 'شارك بحثك الطبي',
      'labelCommunity': 'مجتمع الأطباء',
      'researchSearchHint': 'ابحث في الكتب أو المجلات أو الإرشادات...',
      'trendingTitle': 'رائج وشائع',
      'searchResultsTitle': 'نتائج البحث ({count})',
      'noResultsFound': 'لم يتم العثور على موارد لهذا البحث.',
      'roleDoctor': 'طبيب',
      'roleStudent': 'طالب',
      'rolePatient': 'مريض',
    },
    'ku': {
      'appName': 'MyChart',
      'welcome': 'بەخێربێیت',
      'seeAll': 'بینینی هەموو',
      'doctorInsightsTitle': 'توێژینەوە و تێڕوانینە پزیشکییەکان',
      'doctorInsightsSubtitle': 'ئاگارداربە لە نوێترین توێژینەوە پزیشکییەکان',
      'knowledgeLibraryTitle': 'کتێبخانەی زانیاری',
      'publishResearch': 'بڵاوکردنەوەی توێژینەوە',
      'postResearchTitle': 'توێژینەوەکەت بڵاوبکەرەوە',
      'labelCommunity': 'کۆمەڵگەی پزیشکان',
      'researchSearchHint': 'گەڕان بۆ کتێب یان گۆڤار یان ڕێساکان...',
      'trendingTitle': 'باو و ناسراو',
      'searchResultsTitle': 'ئەنجامەکانی گەڕان ({count})',
      'noResultsFound': 'هیچ سەرچاوەیەک بۆ ئەم گەڕانە نەدۆزرایەوە.',
      'roleDoctor': 'پزیشک',
      'roleStudent': 'خوێندکار',
      'rolePatient': 'نەخۆش',
    },
  };

  static String get(String key, String lang) {
    return _localizedValues[lang]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}
