class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // General
      'appName': 'MyChart',
      'welcome': 'Welcome',
      'back': 'Back',
      'next': 'Next',

      // Welcome Screen
      'getStarted': 'Get Started',
      'studentIdLabel': 'University Email',
      'studentIdHint': 'e.g., username@cihanuniversity.edu.iq',
      'studentPasswordHint': 'Enter your password',
      'studentEmailLoginHint': 'Use your university email to sign in',
      'continueAsGuest': 'Continue as Guest',
      'appTagline': 'Your Health, In Your Hands',
      'featureRecords': 'Records',
      'featureAppointments': 'Appointments',
      'featureMessages': 'Messages',
      'featureHealth': 'Health',
      'navHome': 'Home',
      'navMessages': 'Messages',
      'navChatbot': 'Chatbot AI',
      'navSettings': 'Settings',

      // Modes
      'selectRole': 'Choose Your Role',
      'roleSubtitle': 'Select how you want to access the platform',
      'rolePatient': 'Patient',
      'rolePatientDesc': 'Access medical records & appointments',
      'roleDoctor': 'Doctor',
      'roleDoctorDesc': 'Manage patients & schedules',
      'roleStudent': 'Student',
      'roleStudentDesc': 'Track training & submit reports',

      // Student Dashboard
      'universityTools': 'University Tools',
      'seeAll': 'See All',
      'toolHospital': 'Hospital',
      'toolDoctors': 'Doctors',
      'toolReports': 'Reports',
      'toolTasks': 'Tasks',
      'pendingAssignment': 'Pending Assignment',
      'assignmentDesc':
          'Submit your Clinical Pathology report by 5:00 PM today.',
      'currentLevel': 'Current Level',
      'year4': 'Year 4',
      'modeClinical': 'Clinical',
      'gpaLabel': 'GPA: {value}',
      'idLabel': 'ID: {value}',
      'navCourses': 'My Courses',
      'navCases': 'Cases',
      'commonCases': 'Common Cases',
      'caseStudyTitle': 'Case Study',
      'hospitalInfo': 'Hospital Info',
      'hospitalName': 'Grand City University Hospital',
      'hospitalAddress': '123 Medical Center Blvd, Cityville',
      'labelDepartments': 'Departments',
      'labelBeds': 'Beds',
      'aboutUs': 'About Us',
      'hospitalDesc':
          'Grand City University Hospital is a premier teaching institution dedicated to providing world-class patient care and educating the next generation of healthcare professionals.',
      'closeInfo': 'Close Info',
      'studentName': 'Alex Thompson',
      'titleJoinNewCourse': 'Join New Course',
      'labelNoAvailableCourses': 'No new courses available to join.',
      'actionJoinCourse': 'Join Course',
      'messageJoinSuccess': 'Successfully joined the course!',
      'messageJoinError': 'Failed to join course.',

      // Login
      'loginTitle': 'Welcome Back',
      'loginSubtitle': 'Sign in to your account',
      'emailLabel': 'Email Address',
      'passwordLabel': 'Password',
      'emailHint': 'Enter your email',
      'passwordHint': 'Enter your password',
      'forgotPassword': 'Forgot Password?',
      'signIn': 'Sign In',
      'orSignInWith': 'Or sign in with',
      'dontHaveAccount': 'Don\'t have an account?',
      'signUp': 'Sign Up',

      // Forgot Password
      'forgotPasswordTitle': 'Reset Password',
      'forgotPasswordSubtitle':
          'Enter your credentials to recover your account',
      'sendResetLink': 'Send Reset Link',
      'checkEmail': 'Check your email for instructions',
      'backToLogin': 'Back to Login',
      'identifierLabel': 'Student ID / Email',
      'doctorIdentifierLabel': 'Sheet ID / Email',
      'verificationTitle': 'Verify Code',
      'verificationSubtitle': 'Enter the 6-digit code sent to your email',
      'verifyControl': 'Verify',

      // Profile
      'titleProfile': 'My Profile',
      'labelEmailAddress': 'Email Address',
      'labelPhoneNumber': 'Phone Number',
      'actionEditProfile': 'Edit Profile',
      'gpa': 'GPA',
      'studentId': 'STUDENT ID',

      // Dialogs & Extras
      'labelSubmitReport': 'Submit Report',
      'labelHistory': 'View Submitted Reports',
      'labelReportTitle': 'Report Title',
      'hintReportTitle': 'e.g., Clinical Pathology Report',
      'labelReportDesc': 'Description',
      'hintReportDesc': 'Brief description of your report...',
      'labelAttachFile': 'Attach File',
      'msgFileFormat': 'PDF, DOC, DOCX (Max 10MB)',
      'actionBrowse': 'Browse',
      'actionSubmit': 'Submit',
      'msgReportSubmitted': 'Report submitted successfully!',
      'titleSubmittedReports': 'Submitted Reports',
      'titleAssignments': 'Assignments',
      'labelDue': 'Due: {date}',
      'actionUploadAssignment': 'Upload New Assignment',
      'descUploadAssignment': 'Submit extra credit work',
      'actionView': 'View',
      'titleMarkAttendance': 'Mark Attendance',
      'descScanQR':
          'Scan the QR code in your classroom or clinic to mark your attendance.',
      'actionScanQR': 'Scan QR Code',
      'msgAttendanceMarked': 'Attendance marked successfully!',
      'labelAttendance': 'Attendance',
      'resendCode': 'Resend Code',
      'newPasswordTitle': 'New Password',
      'newPasswordSubtitle': 'Set a strong password for your account',
      'newPasswordLabel': 'New Password',
      'confirmNewPasswordLabel': 'Confirm New Password',
      'newPasswordHint': 'Min. 6 characters',
      'resetSuccess': 'Password changed successfully',
      'passwordMismatch': 'Passwords do not match',

      // Sign Up
      'signUpTitle': 'Create Account',
      'signUpSubtitle': 'Start your health journey today',
      'fullNameLabel': 'Full Name',
      'phoneLabel': 'Phone Number',
      'confirmPasswordLabel': 'Confirm Password',
      'fullNameHint': 'Enter your full name',
      'phoneHint': 'Enter your phone number',
      'confirmPasswordHint': 'Re-enter your password',
      'alreadyHaveAccount': 'Already have an account?',

      // Dashboard
      'patientInfo': 'Patient Information',
      'details': 'Details',
      'demographics': 'Demographics',
      'bloodType': 'Blood Type',
      'chronicDiseases': 'Chronic Diseases',
      'quickActions': 'Quick Actions',
      'bookAppt': 'Book Appointment',
      'medicalRecords': 'Medical Records',
      'labResults': 'Lab Results',
      'pharmacy': 'Pharmacy',
      'upcomingAppt': 'Upcoming Appointment',
      'viewDetails': 'View Details',
      'confirmed': 'Confirmed',
      'allResults': 'All Results',
      'socialStatus': 'Social Status',
      'socialStatusVal': 'Married, Engineer',
      'ageVal': 'Female, 34 yrs',
      'medicalRecordsShort': 'Med Records',
      'pharmacyShort': 'Pharmacy',
      'labResultsShort': 'Lab Results',
      'appointmentTime': '',
      'appointmentDate': '',
      'doctorName': '',
      'doctorTitle': '',
      'studentEmailError':
          'Students must use a university email (@cihanuniversity.edu.iq)',
      'sheetIdLabel': 'Sheet ID',
      'sheetIdHint': 'Enter Sheet ID',
      'emailToggle': 'Email',
      'sheetIdToggle': 'Sheet ID',
      'errorEnterIdOrEmail': 'Please enter your ID or Email',
      'errorEnterPassword': 'Please enter password',
      'errorEnterSheetId': 'Please enter Sheet ID',
      'errorEnterEmail': 'Please enter email',
      'errorInvalidEmail': 'Invalid email format',

      // Doctor Dashboard
      'navPatients': 'Patients',
      'navSchedule': 'Schedule',
      'doctorPatientListTitle': 'Your Patient List',
      'doctorInsightsTitle': 'Medical Research & Insights',
      'doctorInsightsSubtitle': 'Stay updated with the latest clinical studies',
      'statTotalPatients': 'Total Patients',
      'statCompletedToday': 'Completed Today',
      'statPendingReviews': 'Pending Reviews',
      'statTodaysAppointments': 'Today\'s Appointments',
      // Doctor Patients
      'doctorMyPatientsTitle': 'My Patients',
      'doctorAddPatientTitle': 'Add New Patient',
      'labelPatientName': 'Patient Name',
      'labelAge': 'Age',
      'labelCondition': 'Condition',
      'actionAddPatient': 'Add Patient',
      'msgPatientAdded': 'Patient added successfully',
      'labelLastVisit': 'Last visit',
      // Doctor Schedule
      'doctorScheduleTitle': 'Schedule',
      'tabUpcoming': 'Upcoming',
      'tabCompleted': 'Completed',
      'tabCancelled': 'Cancelled',
      'msgNoAppointments': 'No appointments found',
      'actionJoin': 'Join',
      'actionConfirm': 'Confirm',
      'msgAppointmentConfirmed': 'Appointment confirmed',
      'msgAppointmentCancelled': 'Appointment cancelled',
      'labelDuration': 'Duration',
      // Doctor Profile
      'doctorProfileTitle': 'Profile Info',
      'msgProfileUpdated': 'Profile updated successfully',
      'labelPhone': 'Phone',
      'labelDOB': 'Date of Birth',
      'labelSpecialization': 'Specialization',
      'labelLocation': 'Location',
      'labelNotSet': 'Not set',
      // Patient Names
      'patAhmed': 'Ahmed Karim',
      'patSara': 'Sara Omar',
      'patMohamed': 'Mohamed Ali',
      'patLaila': 'Laila Hassan',
      'patYoussef': 'Youssef Ibrahim',
      'patMona': 'Mona Ahmed',
      // Relative Dates & Time
      'timeAgo_justNow': 'Just now',
      'timeAgo_yesterday': 'Yesterday',
      'timeAgo_daysAgo': 'days ago',
      'timeAgo_today': 'Today',
      'timeAgo_weekAgo': 'week ago',
      'timePeriod_am': 'AM',
      'timePeriod_pm': 'PM',
      'labelYears': 'yrs',
      'typeVideo': 'Video Consultation',
      'typeInPerson': 'In-Person Visit',
      'typeFollowUp': 'Follow-up',
      'typeEmergency': 'Emergency',
      'unitMin': 'min',
      'condHypertension': 'Hypertension',
      'condPostSurgery': 'Post-surgery',
      'condInfluenza': 'Influenza',
      'condDiabetes2': 'Diabetes Type 2',
      'condCardiology': 'Cardiology Checkup',
      'sectSecurityUpdate': 'Security Update',
      'subSecurityUpdate':
          'Choose a strong password to protect your professional account.',
      'labelCurrentPassword': 'Current Password',
      'labelNewPassword': 'New Password',
      'labelConfirmNewPassword': 'Confirm New Password',
      'actionUpdatePassword': 'Update Password',
      'msgPasswordUpdated': 'Password updated successfully!',
      'errorRequired': 'Required',
      'errorPasswordShort': 'Password too short (min 6 characters)',
      'errorPasswordsMismatch': 'Passwords do not match',
      'specCardiology': 'Cardiology',
      'locNewYork': 'New York, USA',

      // Patient Dashboard Extra
      'healthUpdate': 'Health Update',
      'labPendingReview':
          'You have {count} pending lab results that need review.',
      'activeCount': '{count} Active',
      'manageProfile': 'Manage your profile',

      // Medical Records
      'tabOverview': 'Overview',
      'tabConditions': 'Conditions',
      'tabMedications': 'Medications',
      'tabVitals': 'Vitals',
      'tabVisits': 'Visits',
      'searchRecords': 'Search records...',
      'labelDiagnosis': 'Diagnosis',
      'labelDiagnosedDate': 'Diagnosed Date',
      'labelFrequency': 'Frequency',
      'labelRoute': 'Route',
      'labelInstructions': 'Instructions',
      'labelReading': 'Reading',
      'labelSource': 'Source',
      'labelType': 'Type',
      'labelNotes': 'Notes',

      // Booking
      'selectSpecialty': 'SELECT SPECIALTY',
      'searchDoctor': 'Search doctor by name...',
      'selectDateTime': 'SELECT DATE & TIME',
      'confirmAppt': 'CONFIRM APPOINTMENT',
      'apptSuccessTitle': 'Appointment Confirmed!',
      'apptSuccessDesc': 'Your appointment has been successfully scheduled.',

      // Chat
      'labelOnline': 'Online',
      'typeMessageHint': 'Type a message...',
      'typingIndicator': 'Assistant is typing...',
      'chatbotHint': 'Ask about your health...',
      'msgLabResult': 'Lab Result',
      'msgMedication': 'Medication',
      'msgAppointment': 'Appointment',
      'sendToPatient': 'Send to Patient',
      'msgLabResultsAvailable': 'Lab Results Available',
      'labelPrescription': 'Prescription',
      'actionCancel': 'Cancel',
      'labelAt': 'at',
      'labelStatus': 'Status:',
      'labelDate': 'Date:',
      'msgDoctorInitial': 'Hello! How are you feeling today?',
      'msgPatientInitial': 'I\'m doing better, thank you doctor.',
      'msgInitialLast': 'The test results look good. Keep up the good work!',
      'msgPhotoRequest': 'Please send me the updated photos.',
      'msgApptConfirmed': 'Your appointment is confirmed for next Tuesday.',
      'specDermatology': 'Dermatology',
      'specGeneral': 'General Practice',

      // Settings
      'settingsTitle': 'Settings',
      'sectAccount': 'Account',
      'optPersonalInfo': 'Personal Information',
      'subPersonalInfo': 'Update your profile details',
      'optChangePassword': 'Change Password',
      'labelPaymentMethods': 'Payment Methods',
      'sectPreferences': 'Preferences',
      'optPushNotifications': 'Push Notifications',
      'optBiometrics': 'Face ID / Touch ID',
      'labelDoctorMode': 'Doctor Mode',
      'optLanguage': 'Language',
      'sectSupport': 'Support',
      'optHelpCenter': 'Help Center',
      'optAboutApp': 'About App',
      'faq': 'Frequently Asked Questions',
      'contactSupport': 'Contact Support',
      'userGuide': 'User Guide',
      'actionLogOut': 'Log Out',
      'msgDoctorModeUpdated': 'Doctor Mode settings updated',
      'labelEnglish': 'English',
      'labelArabic': 'Arabic',
      'labelKurdish': 'Kurdish',
      'optSecurity': 'Security',
      'subSecurity': 'Change password and security settings',
      'subBiometrics': 'Enable biometric authentication',
      'subNotifications': 'Receive push notifications',

      // Profile & Data Entry
      'myProfileTitle': 'My Profile',
      'statAge': 'AGE',
      'statBlood': 'BLOOD',
      'actionEditMedicalProfile': 'Edit Medical Profile',
      'actionSave': 'Save',
      'sectPersonalInfo': 'Personal Information',
      'sectChronicConditions': 'Chronic Conditions',
      'sectCurrentMedications': 'Current Medications',
      'labelFullName': 'Full Name',
      'labelDOBShort': 'DOB',
      'labelHeight': 'Height',
      'labelWeight': 'Weight',
      'labelSocialStatus': 'Social Status',
      'actionAddCondition': 'Add Condition',
      'actionAddMedication': 'Add Medication',
      'msgNoConditions': 'No chronic conditions added.',
      'msgNoMedications': 'No medications added.',
      'msgMedicalProfileUpdated': 'Medical Profile Updated Successfully!',
      'labelConditionName': 'Condition Name',
      'labelStatusHint': 'Status (e.g., Active)',
      'labelMedicationName': 'Medication Name',
      'labelStrengthHint': 'Strength (e.g., 10mg)',
      'actionAdd': 'Add',
      'labelAgeNormal': 'Age',
      'labelBloodType': 'Blood Type',
      'labelNone': 'None',
      'labelComingSoon': 'Coming Soon',
      'labelSingle': 'Single',
      'labelDoctorCount': '{count} doctors available',

      // Lab Results
      'labResultsTitle': 'Lab Results',
      'searchLabTests': 'Search lab tests...',
      'statTotalTests': 'Total Tests',
      'statAbnormal': 'Abnormal',
      'labelRangeValue': 'Range: {range}',
      'labelFilterAll': 'All',
      'labelFilterCompleted': 'Completed',
      'labelFilterPending': 'Pending',
      'labelFilterAbnormal': 'Abnormal',
      'statusNormal': 'Normal',
      'statusHigh': 'High',
      'statusLow': 'Low',
      'statusCritical': 'Critical',
      'statusPartial': 'Partial',
      'statusPending': 'Pending',
      'statusCompleted': 'Completed',

      // Pharmacy
      'pharmacyTitle': 'Pharmacy',
      'preferredPharmacy': 'Preferred Pharmacy',
      'actionNewPrescription': 'New Prescription',
      'tabActiveMeds': 'Active Meds',
      'tabOrderHistory': 'Order History',
      'labelOpenToday': 'Open today: {hours}',
      'labelPillsRemaining': '{count} pills remaining',
      'labelRefillDate': 'Refill: {date}',
      'actionRequestRefill': 'Request Refill',
      'msgRefillRequested': 'Refill requested for {name}',
      'statusProcessing': 'Processing',
      'statusReady': 'Ready',
      'statusPickedUp': 'Picked Up',
      'specAll': 'All',
      'specNeurology': 'Neurology',
      'specOphthalmology': 'Ophthalmology',
      'specOrthopedics': 'Orthopedics',
      'specPediatrics': 'Pediatrics',
      'unitBpm': 'bpm',
      'unitMmHg': 'mmHg',
      'unitLbs': 'lbs',
      'unitMgDl': 'mg/dL',
      'unitTemp': '°F',
      'labelHeartRate': 'Heart Rate',
      'labelBloodPressure': 'Blood Pressure',
      'labelBloodGlucose': 'Blood Glucose',
      'labelToday': 'Today',
      'labelTomorrow': 'Tomorrow',
      'labelSpecialtyAll': 'All',
      'labelSelectDate': 'SELECT DATE',
      'labelSelectTime': 'SELECT TIME',
      'labelDoctorInfo': 'Doctor Info',
      'labelPatientMode': 'PATIENT',
      'labelDone': 'Done',
      'labelBPTrend': 'Blood Pressure Trend',
      'labelHRTrend': 'Heart Rate Trend',
      'labelWeightTrend': 'Weight Trend',
      'labelBGTrend': 'Blood Glucose Trend',
      'labelSystolic': 'Systolic (top)',
      'labelDiastolic': 'Diastolic (bottom)',
      'msgSuccess': 'Success',
      'treatingPhysician': 'Treating Physician',
      'managementPlan': 'Management Plan',
      'lastUpdated': 'Last Updated',
      'labelStartDate': 'Start Date',
      'labelQuantityRemaining': 'Quantity Remaining',
      'labelReason': 'Reason',
      'requestRefill': 'Request Refill',
      'labelDepartment': 'Department',
      'labelSymptomsDuration': 'Symptoms Duration',
      'labelAssessment': 'Assessment',
      'labelTreatmentPlan': 'Treatment Plan',
      'labelProcedures': 'Procedures Performed',
      'labelFollowUp': 'Follow-up Instructions',
      'labelNextAppointment': 'Next Appointment',
      'quickAddVitals': 'Quick Add Vitals',
      'success': 'Success',
      'save': 'Save',
      'labelRefillNeeded': 'Refill needed in {count} days',
      'labelPills': 'pills',
      'bookingTitle': 'Book Appointment',
      'labelNextAvailable': 'Next available:',
      'profileTitle': 'My Profile',
      'labelPatient': 'PATIENT',
      'labelBlood': 'BLOOD',
      'unitYears': 'yrs',

      // Student - Edit Profile
      'titleEditProfile': 'Edit Profile',
      'labelAcademicDetails': 'Academic Details',
      'labelSemester': 'Current Semester',
      'labelAboutMe': 'About Me',
      'labelBio': 'Bio',
      'msgProfileUpdatedStudent': 'Profile updated successfully!',
      'hintEnterName': 'Please enter Full Name',

      // Student - Change Password
      'titleChangePassword': 'Change Password',
      'titleSecurityUpdate': 'Security Update',
      'subSecurityUpdateStudent':
          'Choose a strong password to protect your student account.',
      'labelConfirmPassword': 'Confirm New Password',
      'errPasswordShort': 'Password too short (min 6 characters)',
      'errPasswordMismatch': 'Passwords do not match',

      // Student - My Courses
      'titleMyCourses': 'My Courses',
      'labelSemester1_2026': 'Semester 1, 2026',
      'labelResumeLearning': 'Resume Learning',
      'labelProgress': 'Progress',
      'labelGrade': 'Grade: {grade}',
      'labelInProgress': 'In Progress',
      'labelNext': 'Next: {time}',
      'actionViewDetails': 'View Details',

      // Student - Case Study
      'labelCaseStudy': 'CASE STUDY #{id}',
      'labelCardiology': 'CARDIOLOGY',
      'titleCaseStudy': 'Acute Chest Pain in a 58-Year-Old Male',
      'labelCaseDuration': '45 min case',
      'labelPriority': 'High Priority',
      'tabClinical': 'Clinical',
      'tabLabs': 'Labs',
      'tabDiagnosis': 'Diagnosis',
      'labelChiefComplaint': 'Chief Complaint & Presentation',
      'labelPatientDemographics': 'Patient Demographics',
      'labelInitialVitals': 'Initial Vital Signs',
      'labelLearningObjectives': 'Learning Objectives',

      // Student - Weekly Schedule
      'titleWeeklySchedule': 'Weekly Schedule',
      'labelTodayClasses': 'Today\'s Classes',
      'labelUpcoming': 'Upcoming',
      'labelWeek': 'Week',
      'labelEvents': 'events',
      'actionExport': 'Export',
      'actionShare': 'Share',
      'actionAddEvent': 'Add Event',
      'labelLegend': 'Legend',
      'labelClass': 'Class',
      'labelRotation': 'Rotation',
      'labelStudy': 'Study',
      'labelAppointment': 'Appointment',
      'labelBreak': 'Break',
      'labelExam': 'Exam',
      'labelMeeting': 'Meeting',

      // Student - Course Details
      'tabSyllabus': 'Syllabus',
      'tabAssignments': 'Assignments',
      'tabResources': 'Resources',
      'labelCourseOverview': 'Course Overview',
      'labelModules': 'Modules',
      'labelModule': 'Module',

      'actionContactInstructor': 'Contact Instructor',
      'msgContactingInstructor': 'Contacting instructor...',
    },

    'ar': {
      // General
      'appName': 'ماي تشارت',
      'welcome': 'مرحباً',
      'back': 'رجوع',
      'next': 'التالي',

      // Welcome Screen
      'getStarted': 'ابدأ الآن',
      'studentIdLabel': 'البريد الجامعي',
      'studentIdHint': 'username@cihanuniversity.edu.iq',
      'studentPasswordHint': 'أدخل كلمة المرور',
      'studentEmailLoginHint': 'استخدم بريدك الجامعي لتسجيل الدخول',
      'continueAsGuest': 'متابعة كزائر',
      'appTagline': 'رعايتك الصحية في متناول يدك',
      'featureRecords': 'سجلات',
      'featureAppointments': 'مواعيد',
      'featureMessages': 'رسائل',
      'featureHealth': 'صحة',

      // Modes
      'selectRole': 'اختر نوع الحساب',
      'roleSubtitle': 'كيف ترغب في استخدام المنصة؟',
      'rolePatient': 'مريض',
      'rolePatientDesc': 'الوصول للسجلات الطبية والمواعيد',
      'roleDoctor': 'طبيب',
      'roleDoctorDesc': 'إدارة المرضى والجداول الزمنية',
      'roleStudent': 'طالب',
      'roleStudentDesc': 'متابعة التدريب وتقديم التقارير',

      // Student Dashboard
      'universityTools': 'أدوات الجامعة',
      'seeAll': 'عرض الكل',
      'toolHospital': 'المستشفى',
      'toolDoctors': 'الأطباء',
      'toolReports': 'التقارير',
      'toolTasks': 'المهام',
      'pendingAssignment': 'واجب معلق',
      'assignmentDesc':
          'قدم تقرير علم الأمراض السريري بحلول الساعة ٥:٠٠ مساءً اليوم.',
      'currentLevel': 'المستوى الحالي',
      'year4': 'السنة الرابعة',
      'modeClinical': 'سريري',
      'gpaLabel': 'المعدل: {value}',
      'idLabel': 'الرقم: {value}',
      'navCourses': 'موادي',
      'navCases': 'حالات',
      'commonCases': 'حالات شائعة',
      'caseStudyTitle': 'دراسة حالة',
      'hospitalInfo': 'معلومات المستشفى',
      'hospitalName': 'مستشفى جراند سيتي الجامعي',
      'hospitalAddress': '١٢٣ شارع المركز الطبي، سيتيفيل',
      'labelDepartments': 'الأقسام',
      'labelBeds': 'الأسرة',
      'aboutUs': 'معلومات عنا',
      'hospitalDesc':
          'مستشفى جراند سيتي الجامعي هو مؤسسة تعليمية رائدة مكرسة لتقديم رعاية صحية عالمية المستوى وتعليم الجيل القادم من المتخصصين في الرعاية الصحية.',
      'closeInfo': 'إغلاق',
      'studentName': 'أليكس طومسون',
      'titleJoinNewCourse': 'انضم إلى دورة جديدة',
      'labelNoAvailableCourses': 'لا توجد دورات جديدة متاحة للانضمام.',
      'actionJoinCourse': 'انضم للدورة',
      'messageJoinSuccess': 'تم الانضمام إلى الدورة بنجاح!',
      'messageJoinError': 'فشل الانضمام إلى الدورة.',

      // Login
      'loginTitle': 'مرحباً بعودتك',
      'loginSubtitle': 'سجل دخولك للمتابعة',
      'emailLabel': 'البريد الإلكتروني',
      'passwordLabel': 'كلمة المرور',
      'emailHint': 'أدخل بريدك الإلكتروني',
      'passwordHint': 'أدخل كلمة المرور',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'signIn': 'تسجيل الدخول',
      'orSignInWith': 'أو سجل الدخول عبر',
      'dontHaveAccount': 'ليس لديك حساب؟',
      'signUp': 'إنشاء حساب',

      // Forgot Password
      'forgotPasswordTitle': 'إعادة تعيين كلمة المرور',
      'forgotPasswordSubtitle': 'أدخل بياناتك لاستعادة حسابك',
      'sendResetLink': 'إرسال رابط الإعادة',
      'checkEmail': 'يرجى التحقق من بريدك الإلكتروني للحصول على التعليمات',
      'backToLogin': 'العودة لتسجيل الدخول',
      'identifierLabel': 'الرقم الجامعي / البريد الإلكتروني',
      'doctorIdentifierLabel': 'رقم الورقة / البريد الإلكتروني',
      'verificationTitle': 'تحقق من الرمز',
      'verificationSubtitle': 'أدخل الرمز المكون من 6 أرقام المرسل إلى بريدك',
      'verifyControl': 'تحقق',

      // Profile
      'titleProfile': 'الملف الشخصي',
      'labelEmailAddress': 'البريد الإلكتروني',
      'labelPhoneNumber': 'رقم الهاتف',
      'actionEditProfile': 'تعديل الملف الشخصي',
      'gpa': 'المعدل',
      'studentId': 'رقم الطالب',

      // Dialogs & Extras
      'labelSubmitReport': 'تقديم تقرير',
      'labelHistory': 'عرض التقارير المقدمة',
      'labelReportTitle': 'عنوان التقرير',
      'hintReportTitle': 'مثال: تقرير علم الأمراض السريري',
      'labelReportDesc': 'الوصف',
      'hintReportDesc': 'وصف موجز لتقريرك...',
      'labelAttachFile': 'إرفاق ملف',
      'msgFileFormat': 'PDF, DOC, DOCX (الحد الأقصى ١٠ ميجابايت)',
      'actionBrowse': 'تصفح',
      'actionSubmit': 'إرسال',
      'msgReportSubmitted': 'تم تقديم التقرير بنجاح!',
      'titleSubmittedReports': 'التقارير المقدمة',
      'titleAssignments': 'الواجبات',
      'labelDue': 'تاريخ الاستحقاق: {date}',
      'actionUploadAssignment': 'رفع واجب جديد',
      'descUploadAssignment': 'تقديم عمل إضافي',
      'actionView': 'عرض',
      'titleMarkAttendance': 'تسجيل الحضور',
      'descScanQR': 'امسح رمز QR في قاعتك أو عيادتك لتسجيل حضورك.',
      'actionScanQR': 'مسح رمز QR',
      'msgAttendanceMarked': 'تم تسجيل الحضور بنجاح!',
      'labelAttendance': 'الحضور',
      'resendCode': 'إعادة إرسال الرمز',
      'newPasswordTitle': 'كلمة مرور جديدة',
      'newPasswordSubtitle': 'قم بتعيين كلمة مرور قوية لحسابك',
      'newPasswordLabel': 'كلمة المرور الجديدة',
      'confirmNewPasswordLabel': 'تأكيد كلمة المرور الجديدة',
      'newPasswordHint': '6 أحرف على الأقل',
      'resetSuccess': 'تم تغيير كلمة المرور بنجاح',
      'passwordMismatch': 'كلمات المرور غير متطابقة',

      // Sign Up
      'signUpTitle': 'إنشاء حساب جديد',
      'signUpSubtitle': 'ابدأ رحلتك الصحية اليوم',
      'fullNameLabel': 'الاسم الكامل',
      'phoneLabel': 'رقم الهاتف',
      'confirmPasswordLabel': 'تأكيد كلمة المرور',
      'fullNameHint': 'أدخل اسمك الكامل',
      'phoneHint': 'أدخل رقم هاتفك',
      'confirmPasswordHint': 'أعد إدخال كلمة المرور',
      'alreadyHaveAccount': 'لديك حساب بالفعل؟',

      // Dashboard
      'patientInfo': 'معلومات المريض',
      'details': 'التفاصيل',
      'demographics': 'البيانات الديموغرافية',
      'bloodType': 'فصيلة الدم',
      'chronicDiseases': 'الأمراض المزمنة',
      'quickActions': 'إجراءات سريعة',
      'bookAppt': 'حجز موعد',
      'medicalRecords': 'السجلات الطبية',
      'labResults': 'نتائج المختبر',
      'pharmacy': 'الصيدلية',
      'upcomingAppt': 'الموعد القادم',
      'viewDetails': 'عرض التفاصيل',
      'confirmed': 'مؤكد',
      'allResults': 'كل النتائج',
      'navHome': 'الرئيسية',
      'navMessages': 'الرسائل',
      'navChatbot': 'المساعد الذكي',
      'navSettings': 'الإعدادات',
      'socialStatus': 'الحالة الاجتماعية',
      'socialStatusVal': 'متزوج، مهندس',
      'ageVal': 'أنثى، ٣٤ عاماً',
      'medicalRecordsShort': 'السجلات',
      'pharmacyShort': 'الصيدلية',
      'labResultsShort': 'المختبر',
      'appointmentTime': '',
      'appointmentDate': '',
      'doctorName': '',
      'doctorTitle': '',
      'studentEmailError':
          'يجب على الطلاب استخدام البريد الجامعي (@cihanuniversity.edu.iq)',
      'sheetIdLabel': 'رقم الورقة',
      'sheetIdHint': 'أدخل رقم الورقة',
      'emailToggle': 'البريد',
      'sheetIdToggle': 'رقم الورقة',
      'errorEnterIdOrEmail': 'يرجى إدخال الرقم أو البريد الإلكتروني',
      'errorEnterPassword': 'يرجى إدخال كلمة المرور',
      'errorEnterSheetId': 'يرجى إدخال رقم الورقة',
      'errorEnterEmail': 'يرجى إدخال البريد الإلكتروني',
      'errorInvalidEmail': 'صيغة البريد الإلكتروني غير صحيحة',

      // Doctor Dashboard
      'navPatients': 'المرضى',
      'navSchedule': 'الجدول',
      'doctorPatientListTitle': 'قائمة مرضاك',
      'doctorInsightsTitle': 'الأبحاث والرؤى الطبية',
      'doctorInsightsSubtitle': 'ابق على اطلاع بأحدث الدراسات السريرية',
      'statTotalPatients': 'إجمالي المرضى',
      'statCompletedToday': 'اكتمل اليوم',
      'statPendingReviews': 'مراجعات معلقة',
      'statTodaysAppointments': 'مواعيد اليوم',
      // Doctor Patients
      'doctorMyPatientsTitle': 'مرضاي',
      'doctorAddPatientTitle': 'إضافة مريض جديد',
      'labelPatientName': 'اسم المريض',
      'labelAge': 'العمر',
      'labelCondition': 'الحالة',
      'actionAddPatient': 'إضافة مريض',
      'msgPatientAdded': 'تمت إضافة المريض بنجاح',
      'labelLastVisit': 'آخر زيارة',
      // Doctor Schedule
      'doctorScheduleTitle': 'الجدول',
      'tabUpcoming': 'القادمة',
      'tabCompleted': 'المكتملة',
      'tabCancelled': 'الملغاة',
      'msgNoAppointments': 'لا توجد مواعيد',
      'actionJoin': 'انضمام',
      'actionConfirm': 'تأكيد',
      'msgAppointmentConfirmed': 'تم تأكيد الموعد',
      'msgAppointmentCancelled': 'تم إلغاء الموعد',
      'labelDuration': 'المدة',
      // Doctor Profile
      'doctorProfileTitle': 'معلومات الملف الشخصي',
      'msgProfileUpdated': 'تم تحديث الملف الشخصي بنجاح',
      'labelPhone': 'الهاتف',
      'labelDOB': 'تاريخ الميلاد',
      'labelSpecialization': 'التخصص',
      'labelLocation': 'الموقع',
      'labelNotSet': 'غير محدد',
      // Patient Names
      'patAhmed': 'أحمد كريم',
      'patSara': 'سارة عمر',
      'patMohamed': 'محمد علي',
      'patLaila': 'ليلى حسن',
      'patYoussef': 'يوسف إبراهيم',
      'patMona': 'منى أحمد',
      // Relative Dates & Time
      'timeAgo_justNow': 'الآن',
      'timeAgo_yesterday': 'أمس',
      'timeAgo_daysAgo': 'أيام مضت',
      'timeAgo_today': 'اليوم',
      'timeAgo_weekAgo': 'أسبوع مضى',
      'timePeriod_am': 'ص',
      'timePeriod_pm': 'م',
      'labelYears': 'سنة',
      'typeVideo': 'استشارة فيديو',
      'typeInPerson': 'زيارة شخصية',
      'typeFollowUp': 'متابعة',
      'typeEmergency': 'طوارئ',
      'unitMin': 'دقيقة',
      'condHypertension': 'ارتفاع ضغط الدم',
      'condPostSurgery': 'ما بعد الجراحة',
      'condInfluenza': 'إنفلونزا',
      'condDiabetes2': 'سكري النوع الثاني',
      'condCardiology': 'فحص القلب',
      'sectSecurityUpdate': 'تحديث الأمان',
      'subSecurityUpdate': 'اختر كلمة مرور قوية لحماية حسابك المهني.',
      'labelCurrentPassword': 'كلمة المرور الحالية',
      'labelNewPassword': 'كلمة المرور الجديدة',
      'labelConfirmNewPassword': 'تأكيد كلمة المرور الجديدة',
      'actionUpdatePassword': 'تحديث كلمة المرور',
      'msgPasswordUpdated': 'تم تحديث كلمة المرور بنجاح!',
      'errorRequired': 'مطلوب',
      'errorPasswordShort': 'كلمة المرور قصيرة جداً (٦ أحرف على الأقل)',
      'errorPasswordsMismatch': 'كلمات المرور غير متطابقة',
      'specCardiology': 'أمراض القلب',
      'locNewYork': 'نيويورك، الولايات المتحدة',

      // Patient Dashboard Extra
      'healthUpdate': 'تحديث صحي',
      'labPendingReview': 'لديك {count} من نتائج المختبر بانتظار المراجعة.',
      'activeCount': '{count} نشط',
      'manageProfile': 'إدارة ملفك الشخصي',

      // Medical Records
      'tabOverview': 'نظرة عامة',
      'tabConditions': 'الحالات',
      'tabMedications': 'الأدوية',
      'tabVitals': 'العلامات الحيوية',
      'tabVisits': 'الزيارات',
      'searchRecords': 'البحث في السجلات...',
      'labelDiagnosis': 'التشخيص',
      'labelDiagnosedDate': 'تاريخ التشخيص',
      'labelFrequency': 'التكرار',
      'labelRoute': 'طريقة الاستخدام',
      'labelInstructions': 'التعليمات',
      'labelReading': 'القراءة',
      'labelSource': 'المصدر',
      'labelType': 'النوع',
      'labelNotes': 'ملاحظات',

      // Booking
      'selectSpecialty': 'اختر التخصص',
      'searchDoctor': 'البحث عن طبيب بالاسم...',
      'selectDateTime': 'اختر التاريخ والوقت',
      'confirmAppt': 'تأكيد الموعد',
      'apptSuccessTitle': 'تم تأكيد الموعد!',
      'apptSuccessDesc': 'تم جدولة موعدك بنجاح.',

      // Chat
      'labelOnline': 'متصل الآن',
      'typeMessageHint': 'اكتب رسالة...',
      'typingIndicator': 'المساعد يكتب الآن...',
      'chatbotHint': 'اسأل عن صحتك...',
      'msgLabResult': 'نتيجة مختبر',
      'msgMedication': 'دواء',
      'msgAppointment': 'موعد',
      'sendToPatient': 'إرسال للمريض',
      'msgLabResultsAvailable': 'نتائج المختبر متاحة',
      'labelPrescription': 'وصفة طبية',
      'actionCancel': 'إلغاء',
      'labelAt': 'في',
      'labelStatus': 'الحالة:',
      'labelDate': 'التاريخ:',
      'msgDoctorInitial': 'مرحباً! كيف حالك اليوم؟',
      'msgPatientInitial': 'أنا بخير، شكراً لك يا دكتور.',
      'msgInitialLast': 'تبدو نتائج الاختبار جيدة. استمر في العمل الجيد!',
      'msgPhotoRequest': 'يرجى إرسال الصور المحدثة لي.',
      'msgApptConfirmed': 'تم تأكيد موعدك يوم الثلاثاء القادم.',
      'specDermatology': 'طب الجلدية',
      'specGeneral': 'الطب العام',

      // Settings
      'settingsTitle': 'الإعدادات',
      'sectAccount': 'الحساب',
      'optPersonalInfo': 'المعلومات الشخصية',
      'subPersonalInfo': 'تحديث تفاصيل ملفك الشخصي',
      'optChangePassword': 'تغيير كلمة المرور',
      'labelPaymentMethods': 'طرق الدفع',
      'sectPreferences': 'التفضيلات',
      'optPushNotifications': 'إشعارات الهاتف',
      'optBiometrics': 'بصمة الوجه / الإصبع',
      'labelDoctorMode': 'وضع الطبيب',
      'optLanguage': 'اللغة',
      'sectSupport': 'الدعم',
      'optHelpCenter': 'مركز المساعدة',
      'optAboutApp': 'حول التطبيق',
      'faq': 'الأسئلة الشائعة',
      'contactSupport': 'اتصل بالدعم',
      'userGuide': 'دليل المستخدم',
      'actionLogOut': 'تسجيل الخروج',
      'msgDoctorModeUpdated': 'تم تحديث إعدادات وضع الطبيب',
      'labelEnglish': 'الإنجليزية',
      'labelArabic': 'العربية',
      'labelKurdish': 'الكردية',
      'optSecurity': 'الأمان',
      'subSecurity': 'تغيير كلمة المرور وإعدادات الأمان',
      'subBiometrics': 'تمكين المصادقة البيومترية',
      'subNotifications': 'تلقي إشعارات الهاتف',

      // Profile & Data Entry
      'myProfileTitle': 'ملفي الشخصي',
      'statAge': 'العمر',
      'statBlood': 'الفصيلة',
      'actionEditMedicalProfile': 'تعديل الملف الطبي',
      'actionSave': 'حفظ',
      'sectPersonalInfo': 'المعلومات الشخصية',
      'sectChronicConditions': 'الأمراض المزمنة',
      'sectCurrentMedications': 'الأدوية الحالية',
      'labelFullName': 'الاسم الكامل',
      'labelDOBShort': 'الميلاد',
      'labelHeight': 'الطول',
      'labelWeight': 'الوزن',
      'labelSocialStatus': 'الحالة الاجتماعية',
      'actionAddCondition': 'إضافة حالة',
      'actionAddMedication': 'إضافة دواء',
      'msgNoConditions': 'لم يتم إضافة أمراض مزمنة.',
      'msgNoMedications': 'لم يتم إضافة أدوية.',
      'msgMedicalProfileUpdated': 'تم تحديث الملف الطبي بنجاح!',
      'labelConditionName': 'اسم الحالة',
      'labelStatusHint': 'الحالة (مثلاً: نشط)',
      'labelMedicationName': 'اسم الدواء',
      'labelStrengthHint': 'القوة (مثلاً: ١٠ ملجم)',
      'actionAdd': 'إضافة',
      'labelAgeNormal': 'العمر',
      'labelBloodType': 'فصيلة الدم',
      'labelNone': 'لا يوجد',
      'labelComingSoon': 'قريباً',
      'labelSingle': 'أعزب',
      'labelDoctorCount': '{count} أطباء متاحون',

      // Lab Results
      'labResultsTitle': 'نتائج المختبر',
      'searchLabTests': 'البحث عن تحاليل...',
      'statTotalTests': 'إجمالي التحاليل',
      'statAbnormal': 'غير طبيعي',
      'labelRangeValue': 'المعدل: {range}',
      'labelFilterAll': 'الكل',
      'labelFilterCompleted': 'مكتمل',
      'labelFilterPending': 'قيد الانتظار',
      'labelFilterAbnormal': 'غير طبيعي',
      'statusNormal': 'طبيعي',
      'statusHigh': 'مرتفع',
      'statusLow': 'منخفض',
      'statusCritical': 'حرج',
      'statusPartial': 'جزئي',
      'statusPending': 'قيد الانتظار',
      'statusCompleted': 'مكتمل',

      // Pharmacy
      'pharmacyTitle': 'الصيدلية',
      'preferredPharmacy': 'الصيدلية المفضلة',
      'actionNewPrescription': 'وصفة جديدة',
      'tabActiveMeds': 'الأدوية النشطة',
      'tabOrderHistory': 'سجل الطلبات',
      'labelOpenToday': 'مفتوح اليوم: {hours}',
      'labelPillsRemaining': '{count} حبوب متبقية',
      'labelRefillDate': 'إعادة التعبئة: {date}',
      'actionRequestRefill': 'طلب إعادة تعبئة',
      'msgRefillRequested': 'تم طلب إعادة التعبئة لـ {name}',
      'statusProcessing': 'قيد التنفيذ',
      'statusReady': 'جاهز للامتلام',
      'statusPickedUp': 'تم الاستلام',
      'specAll': 'الكل',
      'specNeurology': 'طب الأعصاب',
      'specOphthalmology': 'طب العيون',
      'specOrthopedics': 'طب العظام',
      'specPediatrics': 'طب الأطفال',
      'unitBpm': 'نبضة/دقيقة',
      'unitMmHg': 'ملم زئبق',
      'unitLbs': 'رطل',
      'unitMgDl': 'ملجم/ديسيليتر',
      'unitTemp': 'م°',
      'labelHeartRate': 'نبض القلب',
      'labelBloodPressure': 'ضغط الدم',
      'labelBloodGlucose': 'سكر الدم',
      'labelToday': 'اليوم',
      'labelTomorrow': 'غداً',
      'labelSpecialtyAll': 'الكل',
      'labelSelectDate': 'اختر التاريخ',
      'labelSelectTime': 'اختر الوقت',
      'labelDoctorInfo': 'معلومات الطبيب',
      'labelPatientMode': 'مريض',
      'labelDone': 'تم',
      'labelBPTrend': 'اتجاه ضغط الدم',
      'labelHRTrend': 'اتجاه نبض القلب',
      'labelWeightTrend': 'اتجاه الوزن',
      'labelBGTrend': 'اتجاه سكر الدم',
      'labelSystolic': 'الانقباضي (العلوي)',
      'labelDiastolic': 'الانبساطي (السفلي)',
      'msgSuccess': 'تم بنجاح',
      'treatingPhysician': 'الطبيب المعالج',
      'managementPlan': 'خطة العلاج',
      'lastUpdated': 'آخر تحديث',
      'labelStartDate': 'تاريخ البدء',
      'labelQuantityRemaining': 'الكمية المتبقية',
      'labelReason': 'السبب',
      'requestRefill': 'طلب إعادة تعبئة',
      'labelDepartment': 'القسم',
      'labelSymptomsDuration': 'مدة الأعراض',
      'labelAssessment': 'التقييم',
      'labelTreatmentPlan': 'خطة العلاج',
      'labelProcedures': 'الإجراءات المنفذة',
      'labelFollowUp': 'تعليمات المتابعة',
      'labelNextAppointment': 'الموعد القادم',
      'quickAddVitals': 'إضافة سريعة للعلامات الحيوية',
      'success': 'تم بنجاح',
      'save': 'حفظ',
      'labelRefillNeeded': 'مطلوب إعادة التعبئة خلال {count} أيام',
      'labelPills': 'حبوب',
      'bookingTitle': 'حجز موعد',
      'labelNextAvailable': 'الموعد المتاح القادم:',
      'profileTitle': 'ملفي الشخصي',
      'labelPatient': 'مريض',
      'labelBlood': 'فصيلة الدم',
      'unitYears': 'سنة',

      // Student - Edit Profile
      'titleEditProfile': 'تعديل الملف الشخصي',
      'labelAcademicDetails': 'التفاصيل الأكاديمية',
      'labelSemester': 'الفصل الدراسي الحالي',
      'labelAboutMe': 'عني',
      'labelBio': 'نبذة',
      'msgProfileUpdatedStudent': 'تم تحديث الملف الشخصي بنجاح!',
      'hintEnterName': 'الرجاء إدخال الاسم الكامل',

      // Student - Change Password
      'titleChangePassword': 'تغيير كلمة المرور',
      'titleSecurityUpdate': 'تحديث الأمان',
      'subSecurityUpdateStudent': 'اختر كلمة مرور قوية لحماية حسابك الطالب.',
      'labelConfirmPassword': 'تأكيد كلمة المرور الجديدة',
      'errPasswordShort': 'كلمة المرور قصيرة جداً (6 أحرف كحد أدنى)',
      'errPasswordMismatch': 'كلمتا المرور غير متطابقتين',

      // Student - My Courses
      'titleMyCourses': 'دوراتي',
      'labelSemester1_2026': 'الفصل الأول، 2026',
      'labelResumeLearning': 'استئناف التعلم',
      'labelProgress': 'التقدم',
      'labelGrade': 'الدرجة: {grade}',
      'labelInProgress': 'قيد التقدم',
      'labelNext': 'التالي: {time}',
      'actionViewDetails': 'عرض التفاصيل',

      // Student - Case Study
      'labelCaseStudy': 'دراسة حالة #{id}',
      'labelCardiology': 'أمراض القلب',
      'titleCaseStudy': 'ألم حاد في الصدر لدى رجل يبلغ من العمر 58 عاماً',
      'labelCaseDuration': 'حالة 45 دقيقة',
      'labelPriority': 'أولوية عالية',
      'tabClinical': 'سريري',
      'tabLabs': 'مختبرات',
      'tabDiagnosis': 'تشخيص',
      'labelChiefComplaint': 'الشكوى الرئيسية والعرض',
      'labelPatientDemographics': 'البيانات الديموغرافية للمريض',
      'labelInitialVitals': 'العلامات الحيوية الأولية',
      'labelLearningObjectives': 'أهداف التعلم',

      // Student - Weekly Schedule
      'titleWeeklySchedule': 'الجدول الأسبوعي',
      'labelTodayClasses': 'محاضرات اليوم',
      'labelUpcoming': 'القادمة',
      'labelWeek': 'أسبوع',
      'labelEvents': 'فعاليات',
      'actionExport': 'تصدير',
      'actionShare': 'مشاركة',
      'actionAddEvent': 'إضافة حدث',
      'labelLegend': 'المفتاح',
      'labelClass': 'محاضرة',
      'labelRotation': 'دورة تدريبية',
      'labelStudy': 'دراسة',
      'labelAppointment': 'موعد',
      'labelBreak': 'استراحة',
      'labelExam': 'اختبار',
      'labelMeeting': 'اجتماع',

      // Student - Course Details
      'tabSyllabus': 'المنهج',
      'tabAssignments': 'الواجبات',
      'tabResources': 'المصادر',
      'labelCourseOverview': 'نظرة عامة على الدورة',
      'labelModules': 'الوحدات',
      'labelModule': 'وحدة',

      'actionContactInstructor': 'تواصل مع المحاضر',
      'msgContactingInstructor': 'جاري التواصل مع المحاضر...',
    },
    'ku': {
      // General
      'appName': 'مای چارت',
      'welcome': 'بەخێربێیت',
      'back': 'گەڕانەوە',
      'next': 'دواتر',

      // Welcome Screen
      'getStarted': 'دەست پێبکە',
      'studentIdLabel': 'ئیمەیڵی زانکۆ',
      'studentIdHint': 'username@cihanuniversity.edu.iq',
      'studentPasswordHint': 'وشەی تێپەڕ بنووسە',
      'studentEmailLoginHint': 'ئیمەیڵی زانکۆت بۆ چوونەژوورەوە بەکاربهێنە',
      'continueAsGuest': 'بەردەوامبە وەک میوان',
      'appTagline': 'چاودێری تەندروستیت لە دەستدا',
      'featureRecords': 'تۆمارەکان',
      'featureAppointments': 'کاتەکان',
      'featureMessages': 'نامەکان',
      'featureHealth': 'تەندروستی',

      // Modes
      'selectRole': 'جۆری هەژمار هەڵبژێرە',
      'roleSubtitle': 'چۆن دەتەوێت پرۆگرامەکە بەکاربهێنیت؟',
      'rolePatient': 'نەخۆش',
      'rolePatientDesc': 'تۆماری پزیشکی و کاتەکان',
      'roleDoctor': 'پزیشک',
      'roleDoctorDesc': 'بەڕێوەبردنی نەخۆش و کاتەکان',
      'roleStudent': 'خوێندکار',
      'roleStudentDesc': 'بەدواداچوونی مەشق و ناردنی ڕاپۆرتەکان',

      // Student Dashboard
      'universityTools': 'ئامرازەکانی زانکۆ',
      'seeAll': 'بینینی هەموو',
      'toolHospital': 'نەخۆشخانە',
      'toolDoctors': 'پزیشکەکان',
      'toolReports': 'ڕاپۆرتەکان',
      'toolTasks': 'ئەرکەکان',
      'pendingAssignment': 'ئەرکی هەڵواسراو',
      'assignmentDesc':
          'ڕاپۆرتی نەخۆشییە پزیشکییەکانت تا کاتژمێر ٥:٠٠ی ئێوارەی ئەمڕۆ بنێرە.',
      'currentLevel': 'ئاستی ئێستا',
      'year4': 'ساڵی چوارەم',
      'modeClinical': 'کلینیکی',
      'gpaLabel': 'GPA: {value}',
      'idLabel': 'ID: {value}',
      'navCourses': 'وانەکانم',
      'navCases': 'حاڵەتەکان',
      'commonCases': 'حاڵەتە باوەکان',
      'caseStudyTitle': 'توێژینەوەی حاڵەت',
      'hospitalInfo': 'زانیاری نەخۆشخانە',
      'hospitalName': 'نەخۆشخانەی زانکۆی گراند سیتی',
      'hospitalAddress': '١٢٣ شەقامی سەنتەری پزیشکی، سیتیڤیل',
      'labelDepartments': 'بەشەکان',
      'labelBeds': 'تەختەکان',
      'aboutUs': 'دەربارەی ئێمە',
      'hospitalDesc':
          'نەخۆشخانەی زانکۆی گراند سیتی دامەزراوەیەکی فێرکاری پێشەنگە کە تەرخانکراوە بۆ پێشکەشکردنی چاودێری نەخۆشی ئاستی جیهانی و پەروەردەکردنی نەوەی داهاتووی پسپۆڕانی تەندروستی.',
      'closeInfo': 'داخستن',
      'studentName': 'ئالێکس تۆمسن',
      'titleJoinNewCourse': 'بەشداری لە کۆرسێکی نوێ بکە',
      'labelNoAvailableCourses': 'هیچ کۆرسێکی نوێ نییە بۆ بەشداریکردن.',
      'actionJoinCourse': 'بەشداری بکە',
      'messageJoinSuccess': 'بە سەرکەوتوویی لە کۆرسەکە بەشداربوویت!',
      'messageJoinError': 'نەتوانرا لە کۆرسەکە بەشداری بکرێت.',

      // Profile
      'titleProfile': 'پرۆفایلی من',
      'labelEmailAddress': 'ناونیشانی ئیمەیڵ',
      'labelPhoneNumber': 'ژمارەی مۆبایل',
      'actionEditProfile': 'دەستکاری پرۆفایل',
      'gpa': 'GPA',
      'studentId': 'ئایدی خوێندکار',

      // Dialogs & Extras
      'labelSubmitReport': 'ناردنی ڕاپۆرت',
      'labelHistory': 'بینینی ڕاپۆرتە نێردراوەکان',
      'labelReportTitle': 'ناونیشانی ڕاپۆرت',
      'hintReportTitle': 'نموونە: ڕاپۆرتی نەخۆشییە پزیشکییەکان',
      'labelReportDesc': 'وەسف',
      'hintReportDesc': 'وەسفێکی کورتی ڕاپۆرتەکەت...',
      'labelAttachFile': 'هاوپێچکردنی فایل',
      'msgFileFormat': 'PDF, DOC, DOCX (زۆرترین ١٠ مێگابایت)',
      'actionBrowse': 'گەڕان',
      'actionSubmit': 'ناردن',
      'msgReportSubmitted': 'ڕاپۆرت بە سەرکەوتوویی نێردرا!',
      'titleSubmittedReports': 'ڕاپۆرتە نێردراوەکان',
      'titleAssignments': 'ئەرکەکان',
      'labelDue': 'بەروار: {date}',
      'actionUploadAssignment': 'بارکردنی ئەرکی نوێ',
      'descUploadAssignment': 'ناردنی کاری زیادە',
      'actionView': 'بینین',
      'titleMarkAttendance': 'تۆمارکردنی ئامادەبوون',
      'descScanQR':
          'کۆدی QR سکانی بکە لە پۆل یان کلینیکەکەت بۆ تۆمارکردنی ئامادەبوون.',
      'actionScanQR': 'سکانی کۆدی QR',
      'msgAttendanceMarked': 'ئامادەبوون بە سەرکەوتوویی تۆمارکرا!',
      'labelAttendance': 'ئامادەبوون',

      // Login
      'loginTitle': 'بەخێربێیتەوە',
      'loginSubtitle': 'چوونەژوورەوە بۆ هەژمارەکەت',
      'emailLabel': 'یمەیڵ',
      'passwordLabel': 'وشەی تێپەڕ',
      'emailHint': 'ئیمەیڵەکەت بنووسە',
      'passwordHint': 'وشەی تێپەڕ بنووسە',
      'forgotPassword': 'وشەی تێپەڕت لەبیرچووە؟',
      'signIn': 'چوونەژوورەوە',
      'orSignInWith': 'یان بچۆ ژوورەوە بە',
      'dontHaveAccount': 'هەژمارت نییە؟',
      'signUp': 'دروستکردنی هەژمار',

      // Forgot Password
      'forgotPasswordTitle': 'گۆڕینی وشەی تێپەڕ',
      'forgotPasswordSubtitle':
          'زانیارییەکانت بنووسە بۆ گەڕاندنەوەی هەژمارەکەت',
      'sendResetLink': 'ناردنی لینکی گۆڕین',
      'checkEmail': 'تکایە سەیری ئیمەیڵەکەت بکە بۆ ڕێنماییەکان',
      'backToLogin': 'گەڕانەوە بۆ چوونەژوورەوە',
      'identifierLabel': 'ناسنامەی خوێندکار / ئیمەیڵ',
      'doctorIdentifierLabel': 'ناسنامەی دکتۆر / ئیمەیڵ',
      'verificationTitle': 'پشکنینی کۆد',
      'verificationSubtitle': 'ئەو کۆدە ٦ ژمارەییەی بۆت ناردووین لێرە بنووسە',
      'verifyControl': 'پشکنین',
      'resendCode': 'ناردنەوەی کۆد',
      'newPasswordTitle': 'وشەی تێپەڕی نوێ',
      'newPasswordSubtitle': 'وشەیەکی تێپەڕی بەهێز لێبدە بۆ هەژمارەکەت',
      'newPasswordLabel': 'وشەی تێپەڕی نوێ',
      'confirmNewPasswordLabel': 'دووبارە بنووسەوە',
      'newPasswordHint': 'بە لایەنی کەم ٦ پیت',
      'resetSuccess': 'وشەی تێپەڕ بە سەرکەوتوویی گۆڕدرا',
      'passwordMismatch': 'وشەی تێپەڕەکان وەک یەک نین',

      // Sign Up
      'signUpTitle': 'هەژماری نوێ',
      'signUpSubtitle': 'گەشتە تەندروستییەکەت دەستپێبکە',
      'fullNameLabel': 'ناوی تەواو',
      'phoneLabel': 'ژمارەی مۆبایل',
      'confirmPasswordLabel': 'دڵنیای وشەی تێپەڕ',
      'fullNameHint': 'ناوی تەواوت بنووسە',
      'phoneHint': 'ژمارەی مۆبایلت بنووسە',
      'confirmPasswordHint': 'وشەی تێپەڕ دووبارە بنووسەوە',
      'alreadyHaveAccount': 'هەژمارت هەیە؟',

      // Dashboard
      'patientInfo': 'زانیاری نەخۆش',
      'details': 'وردەکارییەکان',
      'demographics': 'دیمۆگرافی',
      'bloodType': 'جۆری خوێن',
      'chronicDiseases': 'نەخۆشییە درێژخایەنەکان',
      'quickActions': 'کردارە خێراکان',
      'bookAppt': 'تۆمارکردنی کات',
      'medicalRecords': 'تۆمارە پزیشکییەکان',
      'labResults': 'ئەنجامی پشکنین',
      'pharmacy': 'دەرمانخانە',
      'upcomingAppt': 'کاتی داهاتوو',
      'viewDetails': 'بینینی وردەکاری',
      'confirmed': 'پشتڕاستکراوە',
      'allResults': 'هەموو ئەنجامەکان',
      'navHome': 'سەرەکی',
      'navMessages': 'نامەکان',
      'navChatbot': 'ڕاوێژکاری ژیر',
      'navSettings': 'ڕێکخستنەکان',
      'socialStatus': 'بارودۆخی کۆمەڵایەتی',
      'socialStatusVal': 'هاوسەرگیر، ئەندازیار',
      'ageVal': 'مێ، ٣٤ ساڵ',
      'medicalRecordsShort': 'تۆمارەکان',
      'pharmacyShort': 'دەرمانخانە',
      'labResultsShort': 'تاقیگە',
      'appointmentTime': '١٠:٣٠ بەیانی',
      'appointmentDate': '٢٣ی کانوونی دووەمی ٢٠٢٤',
      'doctorName': 'د. مایکڵ چێن',
      'doctorTitle': 'پسپۆڕی نەخۆشییەکانی دڵ',
      'studentEmailError':
          'قوتابیان دەبێت ئیمەیڵی زانکۆ بەکاربهێنن (@cihanuniversity.edu.iq)',
      'sheetIdLabel': 'ژمارەی پەڕە',
      'sheetIdHint': 'ژمارەی پەڕە بنووسە',
      'emailToggle': 'ئیمەیڵ',
      'sheetIdToggle': 'ژمارەی پەڕە',
      'errorEnterIdOrEmail': 'تکایە ناسنامە یان ئیمەیڵ بنووسە',
      'errorEnterPassword': 'تکایە وشەی تێپەڕ بنووسە',
      'errorEnterSheetId': 'تکایە ژمارەی پەڕە بنووسە',
      'errorEnterEmail': 'تکایە ئیمەیڵ بنووسە',
      'errorInvalidEmail': 'شێوازی ئیمەیڵ هەڵەیە',

      // Doctor Dashboard
      'navPatients': 'نەخۆشەکان',
      'navSchedule': 'خشتە',
      'doctorPatientListTitle': 'لیستی نەخۆشەکانت',
      'doctorInsightsTitle': 'توێژینەوە و تێڕوانینە پزیشکییەکان',
      'doctorInsightsSubtitle': 'ئاگارداربە لە نوێترین توێژینەوە پزیشکییەکان',
      'statTotalPatients': 'کۆی نەخۆشەکان',
      'statCompletedToday': 'تەواوبوو ئەمڕۆ',
      'statPendingReviews': 'پێداچوونەوەی هەڵپەسێردراو',
      'statTodaysAppointments': 'نۆرەکانی ئەمڕۆ',
      // Doctor Patients
      'doctorMyPatientsTitle': 'نەخۆشەکانم',
      'doctorAddPatientTitle': 'زیادکردنی نەخۆشی نوێ',
      'labelPatientName': 'ناوی نەخۆش',
      'labelAge': 'تەمەن',
      'labelCondition': 'بارودۆخ',
      'actionAddPatient': 'زیادکردنی نەخۆش',
      'msgPatientAdded': 'نەخۆش بە سەرکەوتوویی زیادکرا',
      'labelLastVisit': 'دوایین سەردان',
      // Doctor Schedule
      'doctorScheduleTitle': 'خشتە',
      'tabUpcoming': 'داهاتوو',
      'tabCompleted': 'تەواوبوو',
      'tabCancelled': 'هەڵوەشاوە',
      'msgNoAppointments': 'هیچ نۆرەیەک نەدۆزرایەوە',
      'actionJoin': 'بەشداربوون',
      'actionConfirm': 'پەسەندکردن',
      'msgAppointmentConfirmed': 'نۆرە پەسەندکرا',
      'msgAppointmentCancelled': 'نۆرە هەڵوەشایەوە',
      'labelDuration': 'ماوە',
      // Doctor Profile
      'doctorProfileTitle': 'زانیاری پڕۆفایل',
      'msgProfileUpdated': 'پڕۆفایل بە سەرکەوتوویی نوێکرایەوە',
      'labelPhone': 'تەلەفۆن',
      'labelDOB': 'بەرواری لەدایکبوون',
      'labelSpecialization': 'پسپۆڕی',
      'labelLocation': 'ناونیشان',
      'labelNotSet': 'دیاری نەکراوە',
      // Patient Names
      'patAhmed': 'ئەحمەد کەریم',
      'patSara': 'سارە عومەر',
      'patMohamed': 'محەمەد عەلی',
      'patLaila': 'لەیلا حەسەن',
      'patYoussef': 'یوسف ئیبراهیم',
      'patMona': 'مۆنا ئەحمەد',
      // Relative Dates & Time
      'timeAgo_justNow': 'هەر ئێستا',
      'timeAgo_yesterday': 'دوێنێ',
      'timeAgo_daysAgo': 'ڕۆژ لەمەوپێش',
      'timeAgo_today': 'ئەمڕۆ',
      'timeAgo_weekAgo': 'هەفتەیەک پێش ئێستا',
      'timePeriod_am': 'پ.ن',
      'timePeriod_pm': 'د.ن',
      'labelYears': 'ساڵ',
      'typeVideo': 'ڕاوێژی ڤیدیۆیی',
      'typeInPerson': 'سەردانی مەیدانی',
      'typeFollowUp': 'بەدواداچوون',
      'typeEmergency': 'بارودۆخی بەپەلە',
      'unitMin': 'خولەک',
      'condHypertension': 'بەرزبوونەوەی پەستانی خوێن',
      'condPostSurgery': 'دوای نەشتەرگەری',
      'condInfluenza': 'ئەفلۆنزا',
      'condDiabetes2': 'شەکرەی جۆری ٢',
      'condCardiology': 'پشکنینی دڵ',
      'sectSecurityUpdate': 'نوێکردنەوەی ئەمنی',
      'subSecurityUpdate':
          'وشەیەکی تێپەڕی بەهێز هەڵبژێرە بۆ پاراستنی هەژمارە پیشەییەکەت.',
      'labelCurrentPassword': 'وشەی تێپەڕی ئێستا',
      'labelNewPassword': 'وشەی تێپەڕی نوێ',
      'labelConfirmNewPassword': 'دڵنیابوونەوە لە وشەی تێپەڕی نوێ',
      'actionUpdatePassword': 'نوێکردنەوەی وشەی تێپەڕ',
      'msgPasswordUpdated': 'وشەی تێپەڕ بە سەرکەوتوویی نوێکرایەوە!',
      'errorRequired': 'پێویستە',
      'errorPasswordShort': 'وشەی تێپەڕ زۆر کورتە (کەمتر نەبێت لە ٦ پیت)',
      'errorPasswordsMismatch': 'وشەی تێپەڕەکان وەک یەک نین',
      'specCardiology': 'پزیشکی دڵ',
      'locNewYork': 'نیویۆرک، ئەمریکا',

      // Patient Dashboard Extra
      'healthUpdate': 'نوێکردنەوەی تەندروستی',
      'labPendingReview':
          '{count} ئەنجامی پشکنینت هەیە کە پێویستیان بە پێداچوونەوەیە.',
      'activeCount': '{count} چالاک',
      'manageProfile': 'بەڕێوەبردنی پڕۆفایلەکەت',

      // Medical Records
      'tabOverview': 'کورتە',
      'tabConditions': 'بارودۆخەکان',
      'tabMedications': 'دەرمانەکان',
      'tabVitals': 'نیشانە گرنگەکان',
      'tabVisits': 'سەردانەکان',
      'searchRecords': 'گەڕان لە تۆمارەکان...',
      'labelDiagnosis': 'دەستنیشانکردن',
      'labelDiagnosedDate': 'بەرواری دەستنیشانکردن',
      'labelFrequency': 'دووبارەبوونەوە',
      'labelRoute': 'ڕێگەی بەکارهێنان',
      'labelInstructions': 'ڕێنماییەکان',
      'labelReading': 'خوێندنەوە',
      'labelSource': 'سەرچاوە',
      'labelType': 'جۆر',
      'labelNotes': 'تێبینییەکان',

      // Booking
      'selectSpecialty': 'پسپۆڕی هەڵبژێرە',
      'searchDoctor': 'گەڕان بۆ پزیشک بە ناو...',
      'selectDateTime': 'بەروار و کات هەڵبژێرە',
      'confirmAppt': 'پشتڕاستکردنەوەی نۆرە',
      'apptSuccessTitle': 'نۆرە پشتڕاستکرایەوە!',
      'apptSuccessDesc': 'نۆرەکەت بە سەرکەوتوویی تۆمارکرا.',

      // Chat
      'labelOnline': 'ئێستا چالاکە',
      'typeMessageHint': 'نامەیەک بنووسە...',
      'typingIndicator': 'یاریدەدەر خەریکی نووسینە...',
      'chatbotHint': 'دەربارەی تەندروستیت بپرسە...',
      'msgLabResult': 'ئەنجامی تاقیگە',
      'msgMedication': 'دەرمان',
      'msgAppointment': 'ژوان',
      'sendToPatient': 'ناردن بۆ نەخۆش',
      'msgLabResultsAvailable': 'ئەنجامەکانی تاقیگە بەردەستە',
      'labelPrescription': 'ڕەچەتەی پزیشک',
      'actionCancel': 'پاشگەزبوونەوە',
      'labelAt': 'لە',
      'labelStatus': 'بارودۆخ:',
      'labelDate': 'بەروار:',
      'msgDoctorInitial': 'سڵاو! هەست بە چی دەکەیت ئەمڕۆ؟',
      'msgPatientInitial': 'باشترم، سوپاس دکتۆر.',
      'msgInitialLast': 'ئەنجامی پشکنینەکان باشن. بەردەوام بە لەم کارە باشە!',
      'msgPhotoRequest': 'تکایە وێنە نوێکراوەکانم بۆ بنێرە.',
      'msgApptConfirmed': 'نۆرەکەت بۆ سێشەممەی داهاتوو پشتڕاستکرایەوە.',
      'specDermatology': 'نەخۆشییەکانی پێست',
      'specGeneral': 'پزیشکی گشتی',

      // Settings
      'settingsTitle': 'ڕێکخستنەکان',
      'sectAccount': 'هەژمار',
      'optPersonalInfo': 'زانیاری کەسی',
      'subPersonalInfo': 'نوێکردنەوەی پڕۆفایلی کەسی',
      'optChangePassword': 'گۆڕینی وشەی تێپەڕ',
      'labelPaymentMethods': 'ڕێگاکانی پارەدان',
      'sectPreferences': 'هەڵبژاردنەکان',
      'optPushNotifications': 'ئاگادارکردنەوەکان',
      'optBiometrics': 'ناسینەوەی دەموچاو / پەنجەمۆر',
      'labelDoctorMode': 'دۆخی پزیشک',
      'optLanguage': 'زمان',
      'sectSupport': 'پشتیوانی',
      'optHelpCenter': 'سەنتەری یارمەتی',
      'optAboutApp': 'دەربارەی بەرنامە',
      'faq': 'پرسیارە باوەکان',
      'contactSupport': 'پەیوەندی بە پشتگیرییەوە',
      'userGuide': 'ڕێبەری بەکارهێنەر',
      'actionLogOut': 'چوونە دەرەوە',
      'msgDoctorModeUpdated': 'ڕێکخستنەکانی دۆخی پزیشک نوێکرایەوە',
      'labelEnglish': 'ئینگلیزی',
      'labelArabic': 'عەرەبی',
      'labelKurdish': 'کوردی',
      'optSecurity': 'ئاسایش',
      'subSecurity': 'گۆڕینی وشەی تێپەڕ',
      'subBiometrics': 'چالاککردنی چوونەژوورەوە بە پەنجەمۆر',
      'subNotifications': 'وەرگرتنی ئاگادارکردنەوە و نوێکارییەکان',

      // Profile & Data Entry
      'myProfileTitle': 'پڕۆفایلەکەم',
      'statAge': 'تەمەن',
      'statBlood': 'جۆری خوێن',
      'actionEditMedicalProfile': 'دەستکاری پڕۆفایلی پزیشکی',
      'actionSave': 'پاشەکەوتکردن',
      'sectPersonalInfo': 'زانیاری کەسی',
      'sectChronicConditions': 'نەخۆشییە درێژخایەنەکان',
      'sectCurrentMedications': 'دەرمانەکان',
      'labelFullName': 'ناوی تەواو',
      'labelDOBShort': 'بەرواری لەدایکبوون',
      'labelHeight': 'باڵا',
      'labelWeight': 'کێش',
      'labelSocialStatus': 'بارودۆخی کۆمەڵایەتی',
      'actionAddCondition': 'زیادکردنی بارودۆخ',
      'actionAddMedication': 'زیادکردنی دەرمان',
      'msgNoConditions': 'هیچ نەخۆشییەکی درێژخایەن زیاد نەکراوە.',
      'msgNoMedications': 'هیچ دەرمانێک زیاد نەکراوە.',
      'msgMedicalProfileUpdated': 'پڕۆفایلی پزیشکی بە سەرکەوتوویی نوێکرایەوە!',
      'labelConditionName': 'ناوی بارودۆخ',
      'labelStatusHint': 'بارودۆخ (بۆ نموونە: چالاک)',
      'labelMedicationName': 'ناوی دەرمان',
      'labelStrengthHint': 'هێز (بۆ نموونە: ١٠ ملگم)',
      'actionAdd': 'زیادکردن',
      'labelAgeNormal': 'تەمەن',
      'labelBloodType': 'جۆری خوێن',
      'labelNone': 'هیچ',
      'labelComingSoon': 'بەم زووانە',
      'labelSingle': 'سەڵت',
      'labelDoctorCount': '{count} پزیشک بەردەستە',

      // Lab Results
      'labResultsTitle': 'ئەنجامی پشکنینەکان',
      'searchLabTests': 'گەڕان بۆ پشکنینەکان...',
      'statTotalTests': 'کۆی پشکنینەکان',
      'statAbnormal': 'نائاسایی',
      'labelRangeValue': 'مەودا: {range}',
      'labelFilterAll': 'هەموو',
      'labelFilterCompleted': 'تەواوبوو',
      'labelFilterPending': 'هەڵپەسێردراو',
      'labelFilterAbnormal': 'نائاسایی',
      'statusNormal': 'ئاسایی',
      'statusHigh': 'بەرز',
      'statusLow': 'نزم',
      'statusCritical': 'مەترسیدار',
      'statusPartial': 'بەشێکی',
      'statusPending': 'هەڵپەسێردراو',
      'statusCompleted': 'تەواوبوو',

      // Pharmacy
      'pharmacyTitle': 'دەرمانخانە',
      'preferredPharmacy': 'دەرمانخانەی دڵخواز',
      'actionNewPrescription': 'وصفەی نوێ',
      'tabActiveMeds': 'دەرمانە چالاکەکان',
      'tabOrderHistory': 'مێژووی داواکارییەکان',
      'labelOpenToday': 'ئەمڕۆ کراوەیە: {hours}',
      'labelPillsRemaining': '{count} دانە ماوە',
      'labelRefillDate': 'نوێکردنەوە: {date}',
      'actionRequestRefill': 'داواکاری نوێکردنەوە',
      'msgRefillRequested': 'داواکاری نوێکردنەوە بۆ {name} نێردرا',
      'statusProcessing': 'خەریکی جێبەجێکردنە',
      'statusReady': 'ئامادەیە',
      'statusPickedUp': 'وەرگیرا',
      'specAll': 'هەموو',
      'specNeurology': 'پسپۆڕی دەمار',
      'specOphthalmology': 'پسپۆڕی چاو',
      'specOrthopedics': 'پسپۆڕی ئێسک',
      'specPediatrics': 'پسپۆڕی منداڵان',
      'unitBpm': 'لێدان/خولەک',
      'unitMmHg': 'mmHg',
      'unitLbs': 'lbs',
      'unitMgDl': 'mg/dL',
      'unitTemp': 'پلەی سەدی',
      'labelHeartRate': 'لێدانی دڵ',
      'labelBloodPressure': 'پەستانی خوێن',
      'labelBloodGlucose': 'شەکری خوێن',
      'labelToday': 'ئەمڕۆ',
      'labelTomorrow': 'بەیانی',
      'labelSpecialtyAll': 'هەموو',
      'labelSelectDate': 'بەروار هەڵبژێرە',
      'labelSelectTime': 'کات هەڵبژێرە',
      'labelDoctorInfo': 'زانیاری پزیشک',
      'labelPatientMode': 'نەخۆش',
      'labelDone': 'تەواو',
      'labelBPTrend': 'ڕەوتی پەستانی خوێن',
      'labelHRTrend': 'ڕەوتی لێدانی دڵ',
      'labelWeightTrend': 'ڕەوتی کێش',
      'labelBGTrend': 'ڕەوتی شەکری خوێن',
      'labelSystolic': 'پەستانی سەرێ',
      'labelDiastolic': 'پەستانی خوارێ',
      'msgSuccess': 'سەرکەوتوو بوو',
      'treatingPhysician': 'پزیشکی چارەسەرکار',
      'managementPlan': 'پلانی چارەسەر',
      'lastUpdated': 'دوایین نوێکردنەوە',
      'labelStartDate': 'بەرواری دەستپێکردن',
      'labelQuantityRemaining': 'بڕی ماوە',
      'labelReason': 'هۆکار',
      'requestRefill': 'داواکاری نوێکردنەوە',
      'labelDepartment': 'بەش',
      'labelSymptomsDuration': 'ماوەی نیشانەکان',
      'labelAssessment': 'هەڵسەنگاندن',
      'labelTreatmentPlan': 'پلانی چارەسەر',
      'labelProcedures': 'کارە ئەنجامدراوەکان',
      'labelFollowUp': 'ڕێنماییەکانی بەدواداچوون',
      'labelNextAppointment': 'نۆرەی داهاتوو',
      'quickAddVitals': 'زیادکردنی نیشانە گرنگەکان',
      'success': 'سەرکەوتوو بوو',
      'save': 'پاشەکەوتکردن',
      'labelRefillNeeded': 'پێویستی بە نوێکردنەوەیە لە {count} ڕۆژدا',
      'labelPills': 'دانە',
      'bookingTitle': 'نۆرە گرتن',
      'labelNextAvailable': 'کاتی بەردەستی داهاتوو:',
      'profileTitle': 'پڕۆفایلەکەم',
      'labelPatient': 'نەخۆش',

      'labelBlood': 'جۆری خوێن',
      'unitYears': 'ساڵ',

      // Student - Edit Profile
      'titleEditProfile': 'دەستکاری پڕۆفایل',
      'labelAcademicDetails': 'زانیاری ئەکادیمی',
      'labelSemester': 'وەرزی ئێستا',
      'labelAboutMe': 'دەربارەی من',
      'labelBio': 'کورتە',
      'msgProfileUpdatedStudent': 'پڕۆفایل بە سەرکەوتوویی نوێکرایەوە!',
      'hintEnterName': 'تکایە ناوی تەواو بنووسە',

      // Student - Change Password
      'titleChangePassword': 'گۆڕینی وشەی تێپەڕ',
      'titleSecurityUpdate': 'نوێکردنەوەی ئاسایش',
      'subSecurityUpdateStudent':
          'وشەی تێپەڕی بەهێز هەڵبژێرە بۆ پاراستنی هەژمارەکەت.',
      'labelConfirmPassword': 'دووپاتکردنەوەی وشەی تێپەڕی نوێ',
      'errPasswordShort': 'وشەی تێپەڕ زۆر کورتە (لانی کەم ٦ پیت)',
      'errPasswordMismatch': 'وشەی تێپەڕەکان هاوتا نین',

      // Student - My Courses
      'titleMyCourses': 'کۆرسەکانم',
      'labelSemester1_2026': 'وەرزی یەکەم، ٢٠٢٦',
      'labelResumeLearning': 'بەردەوامبوون لە فێربوون',
      'labelProgress': 'پێشکەوتن',
      'labelGrade': 'نمرە: {grade}',
      'labelInProgress': 'لە جێبەجێکردندایە',
      'labelNext': 'داهاتوو: {time}',
      'actionViewDetails': 'پیشاندانی وردەکاری',

      // Student - Case Study
      'labelCaseStudy': 'کەیسی ژمارە #{id}',
      'labelCardiology': 'نەخۆشییەکانی دڵ',
      'titleCaseStudy': 'ئازاری توندی سنگ لە پیاوێکی تەمەن ٥٨ ساڵ',
      'labelCaseDuration': '٤٥ خولەک',
      'labelPriority': 'ئەولەویەتی بەرز',
      'tabClinical': 'کلینیکی',
      'tabLabs': 'تاقیگە',
      'tabDiagnosis': 'دەستنیشانکردن',
      'labelChiefComplaint': 'سکاڵای سەرەکی و نیشانەکان',
      'labelPatientDemographics': 'زانیاری نەخۆش',
      'labelInitialVitals': 'نیشانە سەرەتاییەکان',
      'labelLearningObjectives': 'ئامانجە فێرکارییەکان',

      // Student - Weekly Schedule
      'titleWeeklySchedule': 'خشتەی هەفتانە',
      'labelWeek': 'هەفتە',
      'labelEvents': 'ڕووداوەکان',
      'actionExport': 'هەناردەکردن',
      'actionShare': 'هاوبەشکردن',
      'actionAddEvent': 'زیادکردنی ڕووداو',
      'labelLegend': 'کلیل',
      'labelClass': 'وانە',
      'labelRotation': 'خول',
      'labelStudy': 'خوێندن',
      'labelAppointment': 'کات',
      'labelBreak': 'پشوو',
      'labelExam': 'تاقیکردنەوە',
      'labelMeeting': 'کۆبوونەوە',

      // Student - Course Details
      'tabSyllabus': 'پەیرەو',
      'tabAssignments': 'ئەرکەکان',
      'tabResources': 'سەرچاوەکان',
      'labelCourseOverview': 'پوختەی کۆرس',
      'labelModules': 'یەکەکان',
      'labelModule': 'یەکەی',

      'actionContactInstructor': 'پەیوەندی بە مامۆستاوە بکە',
      'msgContactingInstructor': 'پەیوەندی دەکرێت بە مامۆستاوە...',
    },
  };

  static String get(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}
